// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bp_price_contracts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBPPriceContract = `-- name: CreateBPPriceContract :one

INSERT INTO bp_price_contracts (
    organization_id,
    business_partner_id,
    product_id,
    product_variant_id,
    contract_price,
    discount_percentage,
    min_quantity,
    valid_from,
    valid_to,
    is_active,
    notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, organization_id, business_partner_id, product_id, product_variant_id, contract_price, discount_percentage, min_quantity, valid_from, valid_to, is_active, notes, created_at, updated_at
`

type CreateBPPriceContractParams struct {
	OrganizationID     int32          `json:"organization_id"`
	BusinessPartnerID  int32          `json:"business_partner_id"`
	ProductID          int32          `json:"product_id"`
	ProductVariantID   pgtype.Int4    `json:"product_variant_id"`
	ContractPrice      pgtype.Numeric `json:"contract_price"`
	DiscountPercentage pgtype.Numeric `json:"discount_percentage"`
	MinQuantity        pgtype.Numeric `json:"min_quantity"`
	ValidFrom          pgtype.Date    `json:"valid_from"`
	ValidTo            pgtype.Date    `json:"valid_to"`
	IsActive           pgtype.Bool    `json:"is_active"`
	Notes              pgtype.Text    `json:"notes"`
}

// =====================================================
// B2B PRICE CONTRACT QUERIES
// Tier-1 pricing: negotiated contract prices per business partner + product SKU
// =====================================================
func (q *Queries) CreateBPPriceContract(ctx context.Context, arg CreateBPPriceContractParams) (BpPriceContract, error) {
	row := q.db.QueryRow(ctx, createBPPriceContract,
		arg.OrganizationID,
		arg.BusinessPartnerID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.ContractPrice,
		arg.DiscountPercentage,
		arg.MinQuantity,
		arg.ValidFrom,
		arg.ValidTo,
		arg.IsActive,
		arg.Notes,
	)
	var i BpPriceContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessPartnerID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.ContractPrice,
		&i.DiscountPercentage,
		&i.MinQuantity,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAllContractsForPartner = `-- name: DeactivateAllContractsForPartner :exec
UPDATE bp_price_contracts SET is_active = false
WHERE business_partner_id = $1 AND is_active = true
`

func (q *Queries) DeactivateAllContractsForPartner(ctx context.Context, businessPartnerID int32) error {
	_, err := q.db.Exec(ctx, deactivateAllContractsForPartner, businessPartnerID)
	return err
}

const deactivateBPPriceContract = `-- name: DeactivateBPPriceContract :one
UPDATE bp_price_contracts SET is_active = false WHERE id = $1 RETURNING id, organization_id, business_partner_id, product_id, product_variant_id, contract_price, discount_percentage, min_quantity, valid_from, valid_to, is_active, notes, created_at, updated_at
`

func (q *Queries) DeactivateBPPriceContract(ctx context.Context, id int32) (BpPriceContract, error) {
	row := q.db.QueryRow(ctx, deactivateBPPriceContract, id)
	var i BpPriceContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessPartnerID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.ContractPrice,
		&i.DiscountPercentage,
		&i.MinQuantity,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBPPriceContractForProduct = `-- name: GetBPPriceContractForProduct :one
SELECT bpc.id, bpc.organization_id, bpc.business_partner_id, bpc.product_id, bpc.product_variant_id, bpc.contract_price, bpc.discount_percentage, bpc.min_quantity, bpc.valid_from, bpc.valid_to, bpc.is_active, bpc.notes, bpc.created_at, bpc.updated_at, bp.name AS partner_name
FROM bp_price_contracts bpc
JOIN business_partners bp ON bpc.business_partner_id = bp.id
WHERE bpc.business_partner_id = $1
  AND bpc.product_id = $2
  AND (
    $3::int IS NULL
    OR bpc.product_variant_id = $3::int
    OR bpc.product_variant_id IS NULL
  )
  AND bpc.is_active = true
  AND (bpc.valid_from IS NULL OR bpc.valid_from <= CURRENT_DATE)
  AND (bpc.valid_to IS NULL OR bpc.valid_to >= CURRENT_DATE)
  AND bpc.min_quantity <= COALESCE($4::numeric, 1)
ORDER BY
  bpc.product_variant_id NULLS LAST, -- variant-specific contract preferred over general
  bpc.min_quantity DESC
LIMIT 1
`

type GetBPPriceContractForProductParams struct {
	BusinessPartnerID int32          `json:"business_partner_id"`
	ProductID         int32          `json:"product_id"`
	ProductVariantID  pgtype.Int4    `json:"product_variant_id"`
	Quantity          pgtype.Numeric `json:"quantity"`
}

type GetBPPriceContractForProductRow struct {
	ID                 int32            `json:"id"`
	OrganizationID     int32            `json:"organization_id"`
	BusinessPartnerID  int32            `json:"business_partner_id"`
	ProductID          int32            `json:"product_id"`
	ProductVariantID   pgtype.Int4      `json:"product_variant_id"`
	ContractPrice      pgtype.Numeric   `json:"contract_price"`
	DiscountPercentage pgtype.Numeric   `json:"discount_percentage"`
	MinQuantity        pgtype.Numeric   `json:"min_quantity"`
	ValidFrom          pgtype.Date      `json:"valid_from"`
	ValidTo            pgtype.Date      `json:"valid_to"`
	IsActive           pgtype.Bool      `json:"is_active"`
	Notes              pgtype.Text      `json:"notes"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	PartnerName        string           `json:"partner_name"`
}

// Used in the 3-tier price resolution: Tier 1 (contract) lookup
func (q *Queries) GetBPPriceContractForProduct(ctx context.Context, arg GetBPPriceContractForProductParams) (GetBPPriceContractForProductRow, error) {
	row := q.db.QueryRow(ctx, getBPPriceContractForProduct,
		arg.BusinessPartnerID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.Quantity,
	)
	var i GetBPPriceContractForProductRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessPartnerID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.ContractPrice,
		&i.DiscountPercentage,
		&i.MinQuantity,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartnerName,
	)
	return i, err
}

const listBPPriceContracts = `-- name: ListBPPriceContracts :many
SELECT
    bpc.id, bpc.organization_id, bpc.business_partner_id, bpc.product_id, bpc.product_variant_id, bpc.contract_price, bpc.discount_percentage, bpc.min_quantity, bpc.valid_from, bpc.valid_to, bpc.is_active, bpc.notes, bpc.created_at, bpc.updated_at,
    bp.name AS partner_name,
    bp.code AS partner_code,
    p.name  AS product_name,
    p.sku   AS product_sku
FROM bp_price_contracts bpc
JOIN business_partners bp ON bpc.business_partner_id = bp.id
JOIN products p ON bpc.product_id = p.id
WHERE bpc.organization_id = $1
  AND ($4::int IS NULL OR bpc.business_partner_id = $4::int)
  AND ($5::boolean IS NULL OR bpc.is_active = $5::boolean)
ORDER BY bp.name, p.name
LIMIT $2 OFFSET $3
`

type ListBPPriceContractsParams struct {
	OrganizationID    int32       `json:"organization_id"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
	BusinessPartnerID pgtype.Int4 `json:"business_partner_id"`
	IsActive          pgtype.Bool `json:"is_active"`
}

type ListBPPriceContractsRow struct {
	ID                 int32            `json:"id"`
	OrganizationID     int32            `json:"organization_id"`
	BusinessPartnerID  int32            `json:"business_partner_id"`
	ProductID          int32            `json:"product_id"`
	ProductVariantID   pgtype.Int4      `json:"product_variant_id"`
	ContractPrice      pgtype.Numeric   `json:"contract_price"`
	DiscountPercentage pgtype.Numeric   `json:"discount_percentage"`
	MinQuantity        pgtype.Numeric   `json:"min_quantity"`
	ValidFrom          pgtype.Date      `json:"valid_from"`
	ValidTo            pgtype.Date      `json:"valid_to"`
	IsActive           pgtype.Bool      `json:"is_active"`
	Notes              pgtype.Text      `json:"notes"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	PartnerName        string           `json:"partner_name"`
	PartnerCode        string           `json:"partner_code"`
	ProductName        string           `json:"product_name"`
	ProductSku         string           `json:"product_sku"`
}

func (q *Queries) ListBPPriceContracts(ctx context.Context, arg ListBPPriceContractsParams) ([]ListBPPriceContractsRow, error) {
	rows, err := q.db.Query(ctx, listBPPriceContracts,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.BusinessPartnerID,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBPPriceContractsRow
	for rows.Next() {
		var i ListBPPriceContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.BusinessPartnerID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.ContractPrice,
			&i.DiscountPercentage,
			&i.MinQuantity,
			&i.ValidFrom,
			&i.ValidTo,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartnerName,
			&i.PartnerCode,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBPPriceContract = `-- name: UpdateBPPriceContract :one
UPDATE bp_price_contracts SET
    contract_price      = COALESCE($1, contract_price),
    discount_percentage = COALESCE($2, discount_percentage),
    min_quantity        = COALESCE($3, min_quantity),
    valid_from          = COALESCE($4, valid_from),
    valid_to            = COALESCE($5, valid_to),
    is_active           = COALESCE($6, is_active),
    notes               = COALESCE($7, notes)
WHERE id = $8
RETURNING id, organization_id, business_partner_id, product_id, product_variant_id, contract_price, discount_percentage, min_quantity, valid_from, valid_to, is_active, notes, created_at, updated_at
`

type UpdateBPPriceContractParams struct {
	ContractPrice      pgtype.Numeric `json:"contract_price"`
	DiscountPercentage pgtype.Numeric `json:"discount_percentage"`
	MinQuantity        pgtype.Numeric `json:"min_quantity"`
	ValidFrom          pgtype.Date    `json:"valid_from"`
	ValidTo            pgtype.Date    `json:"valid_to"`
	IsActive           pgtype.Bool    `json:"is_active"`
	Notes              pgtype.Text    `json:"notes"`
	ID                 int32          `json:"id"`
}

func (q *Queries) UpdateBPPriceContract(ctx context.Context, arg UpdateBPPriceContractParams) (BpPriceContract, error) {
	row := q.db.QueryRow(ctx, updateBPPriceContract,
		arg.ContractPrice,
		arg.DiscountPercentage,
		arg.MinQuantity,
		arg.ValidFrom,
		arg.ValidTo,
		arg.IsActive,
		arg.Notes,
		arg.ID,
	)
	var i BpPriceContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessPartnerID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.ContractPrice,
		&i.DiscountPercentage,
		&i.MinQuantity,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
