// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_partners.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultPartnerAddresses = `-- name: ClearDefaultPartnerAddresses :exec
UPDATE partner_addresses
SET is_default = false
WHERE partner_id = $1 AND id != $2
`

type ClearDefaultPartnerAddressesParams struct {
	PartnerID int32 `json:"partner_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) ClearDefaultPartnerAddresses(ctx context.Context, arg ClearDefaultPartnerAddressesParams) error {
	_, err := q.db.Exec(ctx, clearDefaultPartnerAddresses, arg.PartnerID, arg.ID)
	return err
}

const clearPrimaryPartnerContacts = `-- name: ClearPrimaryPartnerContacts :exec
UPDATE partner_contacts
SET is_primary = false
WHERE partner_id = $1 AND id != $2
`

type ClearPrimaryPartnerContactsParams struct {
	PartnerID int32 `json:"partner_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) ClearPrimaryPartnerContacts(ctx context.Context, arg ClearPrimaryPartnerContactsParams) error {
	_, err := q.db.Exec(ctx, clearPrimaryPartnerContacts, arg.PartnerID, arg.ID)
	return err
}

const createBusinessPartner = `-- name: CreateBusinessPartner :one

INSERT INTO business_partners (
    organization_id,
    code,
    name,
    partner_role,
    tax_id,
    currency_code,
    credit_limit,
    outstanding_balance,
    payment_terms_id,
    sales_rep_user_id,
    is_active,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at
`

type CreateBusinessPartnerParams struct {
	OrganizationID     int32           `json:"organization_id"`
	Code               string          `json:"code"`
	Name               string          `json:"name"`
	PartnerRole        string          `json:"partner_role"`
	TaxID              pgtype.Text     `json:"tax_id"`
	CurrencyCode       pgtype.Text     `json:"currency_code"`
	CreditLimit        pgtype.Numeric  `json:"credit_limit"`
	OutstandingBalance pgtype.Numeric  `json:"outstanding_balance"`
	PaymentTermsID     pgtype.Int4     `json:"payment_terms_id"`
	SalesRepUserID     pgtype.Int4     `json:"sales_rep_user_id"`
	IsActive           pgtype.Bool     `json:"is_active"`
	Metadata           json.RawMessage `json:"metadata"`
}

// =====================================================
// BUSINESS PARTNERS QUERIES (SQLC)
// =====================================================
func (q *Queries) CreateBusinessPartner(ctx context.Context, arg CreateBusinessPartnerParams) (BusinessPartner, error) {
	row := q.db.QueryRow(ctx, createBusinessPartner,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.PartnerRole,
		arg.TaxID,
		arg.CurrencyCode,
		arg.CreditLimit,
		arg.OutstandingBalance,
		arg.PaymentTermsID,
		arg.SalesRepUserID,
		arg.IsActive,
		arg.Metadata,
	)
	var i BusinessPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.PartnerRole,
		&i.TaxID,
		&i.CurrencyCode,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.PaymentTermsID,
		&i.SalesRepUserID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartnerAddress = `-- name: CreatePartnerAddress :one

INSERT INTO partner_addresses (
    partner_id,
    address_name,
    address_type,
    street,
    city,
    state,
    zip_code,
    country_code,
    is_default
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, partner_id, address_name, address_type, street, city, state, zip_code, country_code, is_default, created_at
`

type CreatePartnerAddressParams struct {
	PartnerID   int32       `json:"partner_id"`
	AddressName string      `json:"address_name"`
	AddressType string      `json:"address_type"`
	Street      pgtype.Text `json:"street"`
	City        pgtype.Text `json:"city"`
	State       pgtype.Text `json:"state"`
	ZipCode     pgtype.Text `json:"zip_code"`
	CountryCode pgtype.Text `json:"country_code"`
	IsDefault   pgtype.Bool `json:"is_default"`
}

// =====================================================
// PARTNER ADDRESSES QUERIES
// =====================================================
func (q *Queries) CreatePartnerAddress(ctx context.Context, arg CreatePartnerAddressParams) (PartnerAddress, error) {
	row := q.db.QueryRow(ctx, createPartnerAddress,
		arg.PartnerID,
		arg.AddressName,
		arg.AddressType,
		arg.Street,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.CountryCode,
		arg.IsDefault,
	)
	var i PartnerAddress
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AddressName,
		&i.AddressType,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CountryCode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createPartnerContact = `-- name: CreatePartnerContact :one

INSERT INTO partner_contacts (
    partner_id,
    first_name,
    last_name,
    email,
    phone,
    position,
    is_primary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, partner_id, first_name, last_name, email, phone, position, is_primary, created_at
`

type CreatePartnerContactParams struct {
	PartnerID int32       `json:"partner_id"`
	FirstName string      `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Position  pgtype.Text `json:"position"`
	IsPrimary pgtype.Bool `json:"is_primary"`
}

// =====================================================
// PARTNER CONTACTS QUERIES
// =====================================================
func (q *Queries) CreatePartnerContact(ctx context.Context, arg CreatePartnerContactParams) (PartnerContact, error) {
	row := q.db.QueryRow(ctx, createPartnerContact,
		arg.PartnerID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Position,
		arg.IsPrimary,
	)
	var i PartnerContact
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBusinessPartner = `-- name: DeleteBusinessPartner :exec
DELETE FROM business_partners
WHERE id = $1
`

func (q *Queries) DeleteBusinessPartner(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBusinessPartner, id)
	return err
}

const deletePartnerAddress = `-- name: DeletePartnerAddress :exec
DELETE FROM partner_addresses
WHERE id = $1
`

func (q *Queries) DeletePartnerAddress(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePartnerAddress, id)
	return err
}

const deletePartnerContact = `-- name: DeletePartnerContact :exec
DELETE FROM partner_contacts
WHERE id = $1
`

func (q *Queries) DeletePartnerContact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePartnerContact, id)
	return err
}

const getBusinessPartner = `-- name: GetBusinessPartner :one
SELECT id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at FROM business_partners
WHERE id = $1
`

func (q *Queries) GetBusinessPartner(ctx context.Context, id int32) (BusinessPartner, error) {
	row := q.db.QueryRow(ctx, getBusinessPartner, id)
	var i BusinessPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.PartnerRole,
		&i.TaxID,
		&i.CurrencyCode,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.PaymentTermsID,
		&i.SalesRepUserID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessPartnerByCode = `-- name: GetBusinessPartnerByCode :one
SELECT id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at FROM business_partners
WHERE organization_id = $1 AND code = $2
`

type GetBusinessPartnerByCodeParams struct {
	OrganizationID int32  `json:"organization_id"`
	Code           string `json:"code"`
}

func (q *Queries) GetBusinessPartnerByCode(ctx context.Context, arg GetBusinessPartnerByCodeParams) (BusinessPartner, error) {
	row := q.db.QueryRow(ctx, getBusinessPartnerByCode, arg.OrganizationID, arg.Code)
	var i BusinessPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.PartnerRole,
		&i.TaxID,
		&i.CurrencyCode,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.PaymentTermsID,
		&i.SalesRepUserID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerAddress = `-- name: GetPartnerAddress :one
SELECT id, partner_id, address_name, address_type, street, city, state, zip_code, country_code, is_default, created_at FROM partner_addresses
WHERE id = $1
`

func (q *Queries) GetPartnerAddress(ctx context.Context, id int32) (PartnerAddress, error) {
	row := q.db.QueryRow(ctx, getPartnerAddress, id)
	var i PartnerAddress
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AddressName,
		&i.AddressType,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CountryCode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getPartnerContact = `-- name: GetPartnerContact :one
SELECT id, partner_id, first_name, last_name, email, phone, position, is_primary, created_at FROM partner_contacts
WHERE id = $1
`

func (q *Queries) GetPartnerContact(ctx context.Context, id int32) (PartnerContact, error) {
	row := q.db.QueryRow(ctx, getPartnerContact, id)
	var i PartnerContact
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const listBusinessPartners = `-- name: ListBusinessPartners :many
SELECT id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at FROM business_partners
WHERE organization_id = $1
ORDER BY name
`

func (q *Queries) ListBusinessPartners(ctx context.Context, organizationID int32) ([]BusinessPartner, error) {
	rows, err := q.db.Query(ctx, listBusinessPartners, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessPartner
	for rows.Next() {
		var i BusinessPartner
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.PartnerRole,
			&i.TaxID,
			&i.CurrencyCode,
			&i.CreditLimit,
			&i.OutstandingBalance,
			&i.PaymentTermsID,
			&i.SalesRepUserID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessPartnersByRole = `-- name: ListBusinessPartnersByRole :many
SELECT id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at FROM business_partners
WHERE organization_id = $1 AND partner_role = $2
ORDER BY name
`

type ListBusinessPartnersByRoleParams struct {
	OrganizationID int32  `json:"organization_id"`
	PartnerRole    string `json:"partner_role"`
}

func (q *Queries) ListBusinessPartnersByRole(ctx context.Context, arg ListBusinessPartnersByRoleParams) ([]BusinessPartner, error) {
	rows, err := q.db.Query(ctx, listBusinessPartnersByRole, arg.OrganizationID, arg.PartnerRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessPartner
	for rows.Next() {
		var i BusinessPartner
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.PartnerRole,
			&i.TaxID,
			&i.CurrencyCode,
			&i.CreditLimit,
			&i.OutstandingBalance,
			&i.PaymentTermsID,
			&i.SalesRepUserID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerAddresses = `-- name: ListPartnerAddresses :many
SELECT id, partner_id, address_name, address_type, street, city, state, zip_code, country_code, is_default, created_at FROM partner_addresses
WHERE partner_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListPartnerAddresses(ctx context.Context, partnerID int32) ([]PartnerAddress, error) {
	rows, err := q.db.Query(ctx, listPartnerAddresses, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerAddress
	for rows.Next() {
		var i PartnerAddress
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.AddressName,
			&i.AddressType,
			&i.Street,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.CountryCode,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerContacts = `-- name: ListPartnerContacts :many
SELECT id, partner_id, first_name, last_name, email, phone, position, is_primary, created_at FROM partner_contacts
WHERE partner_id = $1
ORDER BY is_primary DESC, created_at DESC
`

func (q *Queries) ListPartnerContacts(ctx context.Context, partnerID int32) ([]PartnerContact, error) {
	rows, err := q.db.Query(ctx, listPartnerContacts, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerContact
	for rows.Next() {
		var i PartnerContact
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Position,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBusinessPartners = `-- name: SearchBusinessPartners :many
SELECT id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at FROM business_partners
WHERE organization_id = $1 
  AND (name ILIKE $2 OR code ILIKE $2)
ORDER BY name
LIMIT $3
`

type SearchBusinessPartnersParams struct {
	OrganizationID int32  `json:"organization_id"`
	Name           string `json:"name"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) SearchBusinessPartners(ctx context.Context, arg SearchBusinessPartnersParams) ([]BusinessPartner, error) {
	rows, err := q.db.Query(ctx, searchBusinessPartners, arg.OrganizationID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessPartner
	for rows.Next() {
		var i BusinessPartner
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.PartnerRole,
			&i.TaxID,
			&i.CurrencyCode,
			&i.CreditLimit,
			&i.OutstandingBalance,
			&i.PaymentTermsID,
			&i.SalesRepUserID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleBusinessPartnerActive = `-- name: ToggleBusinessPartnerActive :one
UPDATE business_partners
SET is_active = $2
WHERE id = $1
RETURNING id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at
`

type ToggleBusinessPartnerActiveParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) ToggleBusinessPartnerActive(ctx context.Context, arg ToggleBusinessPartnerActiveParams) (BusinessPartner, error) {
	row := q.db.QueryRow(ctx, toggleBusinessPartnerActive, arg.ID, arg.IsActive)
	var i BusinessPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.PartnerRole,
		&i.TaxID,
		&i.CurrencyCode,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.PaymentTermsID,
		&i.SalesRepUserID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusinessPartner = `-- name: UpdateBusinessPartner :one
UPDATE business_partners
SET 
    code = $2,
    name = $3,
    partner_role = $4,
    tax_id = $5,
    currency_code = $6,
    credit_limit = $7,
    payment_terms_id = $8,
    sales_rep_user_id = $9,
    is_active = $10,
    metadata = $11
WHERE id = $1
RETURNING id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at
`

type UpdateBusinessPartnerParams struct {
	ID             int32           `json:"id"`
	Code           string          `json:"code"`
	Name           string          `json:"name"`
	PartnerRole    string          `json:"partner_role"`
	TaxID          pgtype.Text     `json:"tax_id"`
	CurrencyCode   pgtype.Text     `json:"currency_code"`
	CreditLimit    pgtype.Numeric  `json:"credit_limit"`
	PaymentTermsID pgtype.Int4     `json:"payment_terms_id"`
	SalesRepUserID pgtype.Int4     `json:"sales_rep_user_id"`
	IsActive       pgtype.Bool     `json:"is_active"`
	Metadata       json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateBusinessPartner(ctx context.Context, arg UpdateBusinessPartnerParams) (BusinessPartner, error) {
	row := q.db.QueryRow(ctx, updateBusinessPartner,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.PartnerRole,
		arg.TaxID,
		arg.CurrencyCode,
		arg.CreditLimit,
		arg.PaymentTermsID,
		arg.SalesRepUserID,
		arg.IsActive,
		arg.Metadata,
	)
	var i BusinessPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.PartnerRole,
		&i.TaxID,
		&i.CurrencyCode,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.PaymentTermsID,
		&i.SalesRepUserID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusinessPartnerBalance = `-- name: UpdateBusinessPartnerBalance :one
UPDATE business_partners
SET outstanding_balance = outstanding_balance + $2
WHERE id = $1
RETURNING id, organization_id, code, name, partner_role, tax_id, currency_code, credit_limit, outstanding_balance, payment_terms_id, sales_rep_user_id, is_active, metadata, created_at, updated_at
`

type UpdateBusinessPartnerBalanceParams struct {
	ID                 int32          `json:"id"`
	OutstandingBalance pgtype.Numeric `json:"outstanding_balance"`
}

func (q *Queries) UpdateBusinessPartnerBalance(ctx context.Context, arg UpdateBusinessPartnerBalanceParams) (BusinessPartner, error) {
	row := q.db.QueryRow(ctx, updateBusinessPartnerBalance, arg.ID, arg.OutstandingBalance)
	var i BusinessPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.PartnerRole,
		&i.TaxID,
		&i.CurrencyCode,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.PaymentTermsID,
		&i.SalesRepUserID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePartnerAddress = `-- name: UpdatePartnerAddress :one
UPDATE partner_addresses
SET
    address_name = $2,
    address_type = $3,
    street = $4,
    city = $5,
    state = $6,
    zip_code = $7,
    country_code = $8,
    is_default = $9
WHERE id = $1
RETURNING id, partner_id, address_name, address_type, street, city, state, zip_code, country_code, is_default, created_at
`

type UpdatePartnerAddressParams struct {
	ID          int32       `json:"id"`
	AddressName string      `json:"address_name"`
	AddressType string      `json:"address_type"`
	Street      pgtype.Text `json:"street"`
	City        pgtype.Text `json:"city"`
	State       pgtype.Text `json:"state"`
	ZipCode     pgtype.Text `json:"zip_code"`
	CountryCode pgtype.Text `json:"country_code"`
	IsDefault   pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpdatePartnerAddress(ctx context.Context, arg UpdatePartnerAddressParams) (PartnerAddress, error) {
	row := q.db.QueryRow(ctx, updatePartnerAddress,
		arg.ID,
		arg.AddressName,
		arg.AddressType,
		arg.Street,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.CountryCode,
		arg.IsDefault,
	)
	var i PartnerAddress
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AddressName,
		&i.AddressType,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CountryCode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updatePartnerContact = `-- name: UpdatePartnerContact :one
UPDATE partner_contacts
SET
    first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    position = $6,
    is_primary = $7
WHERE id = $1
RETURNING id, partner_id, first_name, last_name, email, phone, position, is_primary, created_at
`

type UpdatePartnerContactParams struct {
	ID        int32       `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Position  pgtype.Text `json:"position"`
	IsPrimary pgtype.Bool `json:"is_primary"`
}

func (q *Queries) UpdatePartnerContact(ctx context.Context, arg UpdatePartnerContactParams) (PartnerContact, error) {
	row := q.db.QueryRow(ctx, updatePartnerContact,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Position,
		arg.IsPrimary,
	)
	var i PartnerContact
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}
