// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount_analytics_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscountAnalytics = `-- name: CreateDiscountAnalytics :one
INSERT INTO discount_analytics (
    organization_id,
    store_id,
    cashier_id,
    product_id,
    discount_type,
    date,
    month,
    quarter,
    year,
    total_discounts_given,
    transactions_with_discount,
    total_transactions,
    discount_percentage,
    revenue_impact,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
) RETURNING id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at
`

type CreateDiscountAnalyticsParams struct {
	OrganizationID           int32          `json:"organization_id"`
	StoreID                  pgtype.Int4    `json:"store_id"`
	CashierID                pgtype.Int4    `json:"cashier_id"`
	ProductID                pgtype.Int4    `json:"product_id"`
	DiscountType             pgtype.Text    `json:"discount_type"`
	Date                     pgtype.Date    `json:"date"`
	Month                    pgtype.Int4    `json:"month"`
	Quarter                  pgtype.Int4    `json:"quarter"`
	Year                     pgtype.Int4    `json:"year"`
	TotalDiscountsGiven      pgtype.Numeric `json:"total_discounts_given"`
	TransactionsWithDiscount pgtype.Int4    `json:"transactions_with_discount"`
	TotalTransactions        pgtype.Int4    `json:"total_transactions"`
	DiscountPercentage       pgtype.Numeric `json:"discount_percentage"`
	RevenueImpact            pgtype.Numeric `json:"revenue_impact"`
	Metadata                 []byte         `json:"metadata"`
}

func (q *Queries) CreateDiscountAnalytics(ctx context.Context, arg CreateDiscountAnalyticsParams) (DiscountAnalytic, error) {
	row := q.db.QueryRow(ctx, createDiscountAnalytics,
		arg.OrganizationID,
		arg.StoreID,
		arg.CashierID,
		arg.ProductID,
		arg.DiscountType,
		arg.Date,
		arg.Month,
		arg.Quarter,
		arg.Year,
		arg.TotalDiscountsGiven,
		arg.TransactionsWithDiscount,
		arg.TotalTransactions,
		arg.DiscountPercentage,
		arg.RevenueImpact,
		arg.Metadata,
	)
	var i DiscountAnalytic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.CashierID,
		&i.ProductID,
		&i.DiscountType,
		&i.Date,
		&i.Month,
		&i.Quarter,
		&i.Year,
		&i.TotalDiscountsGiven,
		&i.TransactionsWithDiscount,
		&i.TotalTransactions,
		&i.DiscountPercentage,
		&i.RevenueImpact,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDiscountAnalytics = `-- name: DeleteDiscountAnalytics :exec
DELETE FROM discount_analytics
WHERE id = $1
`

func (q *Queries) DeleteDiscountAnalytics(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDiscountAnalytics, id)
	return err
}

const getDiscountAnalytics = `-- name: GetDiscountAnalytics :one
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE id = $1
`

func (q *Queries) GetDiscountAnalytics(ctx context.Context, id int32) (DiscountAnalytic, error) {
	row := q.db.QueryRow(ctx, getDiscountAnalytics, id)
	var i DiscountAnalytic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.CashierID,
		&i.ProductID,
		&i.DiscountType,
		&i.Date,
		&i.Month,
		&i.Quarter,
		&i.Year,
		&i.TotalDiscountsGiven,
		&i.TransactionsWithDiscount,
		&i.TotalTransactions,
		&i.DiscountPercentage,
		&i.RevenueImpact,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscountAnalyticsByCashier = `-- name: GetDiscountAnalyticsByCashier :many
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE organization_id = $1 AND cashier_id = $2
  AND date >= $3 AND date <= $4
ORDER BY date DESC
`

type GetDiscountAnalyticsByCashierParams struct {
	OrganizationID int32       `json:"organization_id"`
	CashierID      pgtype.Int4 `json:"cashier_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDiscountAnalyticsByCashier(ctx context.Context, arg GetDiscountAnalyticsByCashierParams) ([]DiscountAnalytic, error) {
	rows, err := q.db.Query(ctx, getDiscountAnalyticsByCashier,
		arg.OrganizationID,
		arg.CashierID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountAnalytic
	for rows.Next() {
		var i DiscountAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.CashierID,
			&i.ProductID,
			&i.DiscountType,
			&i.Date,
			&i.Month,
			&i.Quarter,
			&i.Year,
			&i.TotalDiscountsGiven,
			&i.TransactionsWithDiscount,
			&i.TotalTransactions,
			&i.DiscountPercentage,
			&i.RevenueImpact,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountAnalyticsByDateRange = `-- name: GetDiscountAnalyticsByDateRange :many
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE organization_id = $1
  AND date >= $2 AND date <= $3
ORDER BY date DESC
`

type GetDiscountAnalyticsByDateRangeParams struct {
	OrganizationID int32       `json:"organization_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDiscountAnalyticsByDateRange(ctx context.Context, arg GetDiscountAnalyticsByDateRangeParams) ([]DiscountAnalytic, error) {
	rows, err := q.db.Query(ctx, getDiscountAnalyticsByDateRange, arg.OrganizationID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountAnalytic
	for rows.Next() {
		var i DiscountAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.CashierID,
			&i.ProductID,
			&i.DiscountType,
			&i.Date,
			&i.Month,
			&i.Quarter,
			&i.Year,
			&i.TotalDiscountsGiven,
			&i.TransactionsWithDiscount,
			&i.TotalTransactions,
			&i.DiscountPercentage,
			&i.RevenueImpact,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountAnalyticsByProduct = `-- name: GetDiscountAnalyticsByProduct :many
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE organization_id = $1 AND product_id = $2
  AND date >= $3 AND date <= $4
ORDER BY date DESC
`

type GetDiscountAnalyticsByProductParams struct {
	OrganizationID int32       `json:"organization_id"`
	ProductID      pgtype.Int4 `json:"product_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDiscountAnalyticsByProduct(ctx context.Context, arg GetDiscountAnalyticsByProductParams) ([]DiscountAnalytic, error) {
	rows, err := q.db.Query(ctx, getDiscountAnalyticsByProduct,
		arg.OrganizationID,
		arg.ProductID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountAnalytic
	for rows.Next() {
		var i DiscountAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.CashierID,
			&i.ProductID,
			&i.DiscountType,
			&i.Date,
			&i.Month,
			&i.Quarter,
			&i.Year,
			&i.TotalDiscountsGiven,
			&i.TransactionsWithDiscount,
			&i.TotalTransactions,
			&i.DiscountPercentage,
			&i.RevenueImpact,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountAnalyticsByStore = `-- name: GetDiscountAnalyticsByStore :many
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE organization_id = $1 AND store_id = $2
  AND date >= $3 AND date <= $4
ORDER BY date DESC
`

type GetDiscountAnalyticsByStoreParams struct {
	OrganizationID int32       `json:"organization_id"`
	StoreID        pgtype.Int4 `json:"store_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDiscountAnalyticsByStore(ctx context.Context, arg GetDiscountAnalyticsByStoreParams) ([]DiscountAnalytic, error) {
	rows, err := q.db.Query(ctx, getDiscountAnalyticsByStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountAnalytic
	for rows.Next() {
		var i DiscountAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.CashierID,
			&i.ProductID,
			&i.DiscountType,
			&i.Date,
			&i.Month,
			&i.Quarter,
			&i.Year,
			&i.TotalDiscountsGiven,
			&i.TransactionsWithDiscount,
			&i.TotalTransactions,
			&i.DiscountPercentage,
			&i.RevenueImpact,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountAnalyticsByType = `-- name: GetDiscountAnalyticsByType :many
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE organization_id = $1 AND discount_type = $2
  AND date >= $3 AND date <= $4
ORDER BY date DESC
`

type GetDiscountAnalyticsByTypeParams struct {
	OrganizationID int32       `json:"organization_id"`
	DiscountType   pgtype.Text `json:"discount_type"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDiscountAnalyticsByType(ctx context.Context, arg GetDiscountAnalyticsByTypeParams) ([]DiscountAnalytic, error) {
	rows, err := q.db.Query(ctx, getDiscountAnalyticsByType,
		arg.OrganizationID,
		arg.DiscountType,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountAnalytic
	for rows.Next() {
		var i DiscountAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.CashierID,
			&i.ProductID,
			&i.DiscountType,
			&i.Date,
			&i.Month,
			&i.Quarter,
			&i.Year,
			&i.TotalDiscountsGiven,
			&i.TransactionsWithDiscount,
			&i.TotalTransactions,
			&i.DiscountPercentage,
			&i.RevenueImpact,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountSummaryByMonth = `-- name: GetDiscountSummaryByMonth :many
SELECT 
    year,
    month,
    SUM(total_discounts_given) AS total_discounts,
    SUM(transactions_with_discount) AS total_transactions_with_discount,
    SUM(total_transactions) AS total_transactions,
    AVG(discount_percentage) AS avg_discount_percentage,
    SUM(revenue_impact) AS total_revenue_impact
FROM discount_analytics
WHERE organization_id = $1
  AND date >= $2 AND date <= $3
GROUP BY year, month
ORDER BY year DESC, month DESC
`

type GetDiscountSummaryByMonthParams struct {
	OrganizationID int32       `json:"organization_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

type GetDiscountSummaryByMonthRow struct {
	Year                          pgtype.Int4 `json:"year"`
	Month                         pgtype.Int4 `json:"month"`
	TotalDiscounts                int64       `json:"total_discounts"`
	TotalTransactionsWithDiscount int64       `json:"total_transactions_with_discount"`
	TotalTransactions             int64       `json:"total_transactions"`
	AvgDiscountPercentage         float64     `json:"avg_discount_percentage"`
	TotalRevenueImpact            int64       `json:"total_revenue_impact"`
}

func (q *Queries) GetDiscountSummaryByMonth(ctx context.Context, arg GetDiscountSummaryByMonthParams) ([]GetDiscountSummaryByMonthRow, error) {
	rows, err := q.db.Query(ctx, getDiscountSummaryByMonth, arg.OrganizationID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiscountSummaryByMonthRow
	for rows.Next() {
		var i GetDiscountSummaryByMonthRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.TotalDiscounts,
			&i.TotalTransactionsWithDiscount,
			&i.TotalTransactions,
			&i.AvgDiscountPercentage,
			&i.TotalRevenueImpact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountSummaryByType = `-- name: GetDiscountSummaryByType :many
SELECT 
    discount_type,
    SUM(total_discounts_given) AS total_discounts,
    SUM(transactions_with_discount) AS total_transactions,
    SUM(revenue_impact) AS total_revenue_impact
FROM discount_analytics
WHERE organization_id = $1
  AND date >= $2 AND date <= $3
GROUP BY discount_type
ORDER BY total_discounts DESC
`

type GetDiscountSummaryByTypeParams struct {
	OrganizationID int32       `json:"organization_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

type GetDiscountSummaryByTypeRow struct {
	DiscountType       pgtype.Text `json:"discount_type"`
	TotalDiscounts     int64       `json:"total_discounts"`
	TotalTransactions  int64       `json:"total_transactions"`
	TotalRevenueImpact int64       `json:"total_revenue_impact"`
}

func (q *Queries) GetDiscountSummaryByType(ctx context.Context, arg GetDiscountSummaryByTypeParams) ([]GetDiscountSummaryByTypeRow, error) {
	rows, err := q.db.Query(ctx, getDiscountSummaryByType, arg.OrganizationID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiscountSummaryByTypeRow
	for rows.Next() {
		var i GetDiscountSummaryByTypeRow
		if err := rows.Scan(
			&i.DiscountType,
			&i.TotalDiscounts,
			&i.TotalTransactions,
			&i.TotalRevenueImpact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopDiscountingCashiers = `-- name: GetTopDiscountingCashiers :many
SELECT 
    cashier_id,
    SUM(total_discounts_given) AS total_discounts,
    SUM(transactions_with_discount) AS total_transactions,
    AVG(discount_percentage) AS avg_discount_percentage
FROM discount_analytics
WHERE organization_id = $1
  AND date >= $2 AND date <= $3
  AND cashier_id IS NOT NULL
GROUP BY cashier_id
ORDER BY total_discounts DESC
LIMIT $4
`

type GetTopDiscountingCashiersParams struct {
	OrganizationID int32       `json:"organization_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
	Limit          int32       `json:"limit"`
}

type GetTopDiscountingCashiersRow struct {
	CashierID             pgtype.Int4 `json:"cashier_id"`
	TotalDiscounts        int64       `json:"total_discounts"`
	TotalTransactions     int64       `json:"total_transactions"`
	AvgDiscountPercentage float64     `json:"avg_discount_percentage"`
}

func (q *Queries) GetTopDiscountingCashiers(ctx context.Context, arg GetTopDiscountingCashiersParams) ([]GetTopDiscountingCashiersRow, error) {
	rows, err := q.db.Query(ctx, getTopDiscountingCashiers,
		arg.OrganizationID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDiscountingCashiersRow
	for rows.Next() {
		var i GetTopDiscountingCashiersRow
		if err := rows.Scan(
			&i.CashierID,
			&i.TotalDiscounts,
			&i.TotalTransactions,
			&i.AvgDiscountPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscountAnalytics = `-- name: ListDiscountAnalytics :many
SELECT id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at FROM discount_analytics
WHERE organization_id = $1
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type ListDiscountAnalyticsParams struct {
	OrganizationID int32 `json:"organization_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

func (q *Queries) ListDiscountAnalytics(ctx context.Context, arg ListDiscountAnalyticsParams) ([]DiscountAnalytic, error) {
	rows, err := q.db.Query(ctx, listDiscountAnalytics, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountAnalytic
	for rows.Next() {
		var i DiscountAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.CashierID,
			&i.ProductID,
			&i.DiscountType,
			&i.Date,
			&i.Month,
			&i.Quarter,
			&i.Year,
			&i.TotalDiscountsGiven,
			&i.TransactionsWithDiscount,
			&i.TotalTransactions,
			&i.DiscountPercentage,
			&i.RevenueImpact,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscountAnalytics = `-- name: UpdateDiscountAnalytics :one
UPDATE discount_analytics
SET 
    total_discounts_given = $2,
    transactions_with_discount = $3,
    total_transactions = $4,
    discount_percentage = $5,
    revenue_impact = $6,
    metadata = $7
WHERE id = $1
RETURNING id, organization_id, store_id, cashier_id, product_id, discount_type, date, month, quarter, year, total_discounts_given, transactions_with_discount, total_transactions, discount_percentage, revenue_impact, metadata, created_at, updated_at
`

type UpdateDiscountAnalyticsParams struct {
	ID                       int32          `json:"id"`
	TotalDiscountsGiven      pgtype.Numeric `json:"total_discounts_given"`
	TransactionsWithDiscount pgtype.Int4    `json:"transactions_with_discount"`
	TotalTransactions        pgtype.Int4    `json:"total_transactions"`
	DiscountPercentage       pgtype.Numeric `json:"discount_percentage"`
	RevenueImpact            pgtype.Numeric `json:"revenue_impact"`
	Metadata                 []byte         `json:"metadata"`
}

func (q *Queries) UpdateDiscountAnalytics(ctx context.Context, arg UpdateDiscountAnalyticsParams) (DiscountAnalytic, error) {
	row := q.db.QueryRow(ctx, updateDiscountAnalytics,
		arg.ID,
		arg.TotalDiscountsGiven,
		arg.TransactionsWithDiscount,
		arg.TotalTransactions,
		arg.DiscountPercentage,
		arg.RevenueImpact,
		arg.Metadata,
	)
	var i DiscountAnalytic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.CashierID,
		&i.ProductID,
		&i.DiscountType,
		&i.Date,
		&i.Month,
		&i.Quarter,
		&i.Year,
		&i.TotalDiscountsGiven,
		&i.TransactionsWithDiscount,
		&i.TotalTransactions,
		&i.DiscountPercentage,
		&i.RevenueImpact,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
