// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_entries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGLAccountMapping = `-- name: CreateGLAccountMapping :one
INSERT INTO gl_account_mappings (organization_id, mapping_type, store_id, gl_account_id)
VALUES ($1, $2, $3, $4) RETURNING id, organization_id, mapping_type, store_id, gl_account_id
`

type CreateGLAccountMappingParams struct {
	OrganizationID int32       `json:"organization_id"`
	MappingType    string      `json:"mapping_type"`
	StoreID        pgtype.Int4 `json:"store_id"`
	GlAccountID    int32       `json:"gl_account_id"`
}

func (q *Queries) CreateGLAccountMapping(ctx context.Context, arg CreateGLAccountMappingParams) (GlAccountMapping, error) {
	row := q.db.QueryRow(ctx, createGLAccountMapping,
		arg.OrganizationID,
		arg.MappingType,
		arg.StoreID,
		arg.GlAccountID,
	)
	var i GlAccountMapping
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MappingType,
		&i.StoreID,
		&i.GlAccountID,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one

INSERT INTO journal_entries (
    organization_id, entry_number, posting_date, reference_type, reference_id, memo
) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, organization_id, entry_number, posting_date, reference_type, reference_id, memo, created_at
`

type CreateJournalEntryParams struct {
	OrganizationID int32       `json:"organization_id"`
	EntryNumber    string      `json:"entry_number"`
	PostingDate    pgtype.Date `json:"posting_date"`
	ReferenceType  string      `json:"reference_type"`
	ReferenceID    string      `json:"reference_id"`
	Memo           pgtype.Text `json:"memo"`
}

// =====================================================
// JOURNAL ENTRIES & GL ACCOUNT MAPPINGS QUERIES
// =====================================================
func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.OrganizationID,
		arg.EntryNumber,
		arg.PostingDate,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Memo,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntryNumber,
		&i.PostingDate,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const createJournalLine = `-- name: CreateJournalLine :one
INSERT INTO journal_lines (
    journal_id, account_id, cost_center_id, debit, credit, memo
) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, journal_id, account_id, cost_center_id, debit, credit, memo
`

type CreateJournalLineParams struct {
	JournalID    int64          `json:"journal_id"`
	AccountID    int32          `json:"account_id"`
	CostCenterID pgtype.Int4    `json:"cost_center_id"`
	Debit        pgtype.Numeric `json:"debit"`
	Credit       pgtype.Numeric `json:"credit"`
	Memo         pgtype.Text    `json:"memo"`
}

func (q *Queries) CreateJournalLine(ctx context.Context, arg CreateJournalLineParams) (JournalLine, error) {
	row := q.db.QueryRow(ctx, createJournalLine,
		arg.JournalID,
		arg.AccountID,
		arg.CostCenterID,
		arg.Debit,
		arg.Credit,
		arg.Memo,
	)
	var i JournalLine
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.AccountID,
		&i.CostCenterID,
		&i.Debit,
		&i.Credit,
		&i.Memo,
	)
	return i, err
}

const deleteGLAccountMapping = `-- name: DeleteGLAccountMapping :exec
DELETE FROM gl_account_mappings WHERE id = $1
`

func (q *Queries) DeleteGLAccountMapping(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGLAccountMapping, id)
	return err
}

const getGLAccountMappingByType = `-- name: GetGLAccountMappingByType :one
SELECT gm.id, gm.organization_id, gm.mapping_type, gm.store_id, gm.gl_account_id, coa.account_code, coa.account_name, coa.account_type
FROM gl_account_mappings gm
JOIN chart_of_accounts coa ON gm.gl_account_id = coa.id
WHERE gm.organization_id = $1
  AND gm.mapping_type = $2
  AND (
    -- Store-specific mapping takes precedence over org-level
    gm.store_id = $3::int
    OR (gm.store_id IS NULL AND NOT EXISTS (
        SELECT 1 FROM gl_account_mappings
        WHERE organization_id = $1 AND mapping_type = $2 AND store_id = $3::int
    ))
  )
ORDER BY gm.store_id NULLS LAST
LIMIT 1
`

type GetGLAccountMappingByTypeParams struct {
	OrganizationID int32       `json:"organization_id"`
	MappingType    string      `json:"mapping_type"`
	StoreID        pgtype.Int4 `json:"store_id"`
}

type GetGLAccountMappingByTypeRow struct {
	ID             int32       `json:"id"`
	OrganizationID int32       `json:"organization_id"`
	MappingType    string      `json:"mapping_type"`
	StoreID        pgtype.Int4 `json:"store_id"`
	GlAccountID    int32       `json:"gl_account_id"`
	AccountCode    string      `json:"account_code"`
	AccountName    string      `json:"account_name"`
	AccountType    string      `json:"account_type"`
}

// Resolve the GL account for a given transaction context.
// Use store_id = NULL for org-level fallback mappings.
func (q *Queries) GetGLAccountMappingByType(ctx context.Context, arg GetGLAccountMappingByTypeParams) (GetGLAccountMappingByTypeRow, error) {
	row := q.db.QueryRow(ctx, getGLAccountMappingByType, arg.OrganizationID, arg.MappingType, arg.StoreID)
	var i GetGLAccountMappingByTypeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MappingType,
		&i.StoreID,
		&i.GlAccountID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountType,
	)
	return i, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, organization_id, entry_number, posting_date, reference_type, reference_id, memo, created_at FROM journal_entries WHERE id = $1
`

func (q *Queries) GetJournalEntry(ctx context.Context, id int64) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntryNumber,
		&i.PostingDate,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalEntryByNumber = `-- name: GetJournalEntryByNumber :one
SELECT id, organization_id, entry_number, posting_date, reference_type, reference_id, memo, created_at FROM journal_entries WHERE entry_number = $1
`

func (q *Queries) GetJournalEntryByNumber(ctx context.Context, entryNumber string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByNumber, entryNumber)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntryNumber,
		&i.PostingDate,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const listGLAccountMappings = `-- name: ListGLAccountMappings :many
SELECT gm.id, gm.organization_id, gm.mapping_type, gm.store_id, gm.gl_account_id, coa.account_code, coa.account_name
FROM gl_account_mappings gm
JOIN chart_of_accounts coa ON gm.gl_account_id = coa.id
WHERE gm.organization_id = $1
ORDER BY gm.mapping_type, gm.store_id NULLS LAST
`

type ListGLAccountMappingsRow struct {
	ID             int32       `json:"id"`
	OrganizationID int32       `json:"organization_id"`
	MappingType    string      `json:"mapping_type"`
	StoreID        pgtype.Int4 `json:"store_id"`
	GlAccountID    int32       `json:"gl_account_id"`
	AccountCode    string      `json:"account_code"`
	AccountName    string      `json:"account_name"`
}

func (q *Queries) ListGLAccountMappings(ctx context.Context, organizationID int32) ([]ListGLAccountMappingsRow, error) {
	rows, err := q.db.Query(ctx, listGLAccountMappings, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGLAccountMappingsRow
	for rows.Next() {
		var i ListGLAccountMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MappingType,
			&i.StoreID,
			&i.GlAccountID,
			&i.AccountCode,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByOrganization = `-- name: ListJournalEntriesByOrganization :many
SELECT je.id, je.organization_id, je.entry_number, je.posting_date, je.reference_type, je.reference_id, je.memo, je.created_at FROM journal_entries je
WHERE je.organization_id = $1
  AND ($4::date IS NULL OR je.posting_date >= $4::date)
  AND ($5::date IS NULL OR je.posting_date <= $5::date)
ORDER BY je.posting_date DESC, je.id DESC
LIMIT $2 OFFSET $3
`

type ListJournalEntriesByOrganizationParams struct {
	OrganizationID int32       `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
}

func (q *Queries) ListJournalEntriesByOrganization(ctx context.Context, arg ListJournalEntriesByOrganizationParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByOrganization,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntryNumber,
			&i.PostingDate,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Memo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByReference = `-- name: ListJournalEntriesByReference :many
SELECT je.id, je.organization_id, je.entry_number, je.posting_date, je.reference_type, je.reference_id, je.memo, je.created_at, json_agg(
    jsonb_build_object(
        'id', jl.id,
        'account_id', jl.account_id,
        'account_code', coa.account_code,
        'account_name', coa.account_name,
        'cost_center_id', jl.cost_center_id,
        'debit', jl.debit,
        'credit', jl.credit,
        'memo', jl.memo
    ) ORDER BY jl.id
) AS lines
FROM journal_entries je
LEFT JOIN journal_lines jl ON jl.journal_id = je.id
LEFT JOIN chart_of_accounts coa ON jl.account_id = coa.id
WHERE je.organization_id = $1
  AND je.reference_type = $2
  AND je.reference_id = $3
GROUP BY je.id
ORDER BY je.posting_date DESC
`

type ListJournalEntriesByReferenceParams struct {
	OrganizationID int32  `json:"organization_id"`
	ReferenceType  string `json:"reference_type"`
	ReferenceID    string `json:"reference_id"`
}

type ListJournalEntriesByReferenceRow struct {
	ID             int64            `json:"id"`
	OrganizationID int32            `json:"organization_id"`
	EntryNumber    string           `json:"entry_number"`
	PostingDate    pgtype.Date      `json:"posting_date"`
	ReferenceType  string           `json:"reference_type"`
	ReferenceID    string           `json:"reference_id"`
	Memo           pgtype.Text      `json:"memo"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	Lines          []byte           `json:"lines"`
}

func (q *Queries) ListJournalEntriesByReference(ctx context.Context, arg ListJournalEntriesByReferenceParams) ([]ListJournalEntriesByReferenceRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByReference, arg.OrganizationID, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalEntriesByReferenceRow
	for rows.Next() {
		var i ListJournalEntriesByReferenceRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntryNumber,
			&i.PostingDate,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Memo,
			&i.CreatedAt,
			&i.Lines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalLinesByEntry = `-- name: ListJournalLinesByEntry :many
SELECT jl.id, jl.journal_id, jl.account_id, jl.cost_center_id, jl.debit, jl.credit, jl.memo, coa.account_code, coa.account_name, coa.account_type
FROM journal_lines jl
JOIN chart_of_accounts coa ON jl.account_id = coa.id
WHERE jl.journal_id = $1
ORDER BY jl.id
`

type ListJournalLinesByEntryRow struct {
	ID           int64          `json:"id"`
	JournalID    int64          `json:"journal_id"`
	AccountID    int32          `json:"account_id"`
	CostCenterID pgtype.Int4    `json:"cost_center_id"`
	Debit        pgtype.Numeric `json:"debit"`
	Credit       pgtype.Numeric `json:"credit"`
	Memo         pgtype.Text    `json:"memo"`
	AccountCode  string         `json:"account_code"`
	AccountName  string         `json:"account_name"`
	AccountType  string         `json:"account_type"`
}

func (q *Queries) ListJournalLinesByEntry(ctx context.Context, journalID int64) ([]ListJournalLinesByEntryRow, error) {
	rows, err := q.db.Query(ctx, listJournalLinesByEntry, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalLinesByEntryRow
	for rows.Next() {
		var i ListJournalLinesByEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountID,
			&i.CostCenterID,
			&i.Debit,
			&i.Credit,
			&i.Memo,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumJournalBalanceByAccount = `-- name: SumJournalBalanceByAccount :one
SELECT
    coa.id AS account_id,
    coa.account_code,
    coa.account_name,
    COALESCE(SUM(jl.debit), 0)  AS total_debit,
    COALESCE(SUM(jl.credit), 0) AS total_credit,
    COALESCE(SUM(jl.debit), 0) - COALESCE(SUM(jl.credit), 0) AS net_balance
FROM chart_of_accounts coa
LEFT JOIN journal_lines jl ON jl.account_id = coa.id
LEFT JOIN journal_entries je ON jl.journal_id = je.id AND je.organization_id = $1
WHERE coa.id = $2
GROUP BY coa.id, coa.account_code, coa.account_name
`

type SumJournalBalanceByAccountParams struct {
	OrganizationID int32 `json:"organization_id"`
	ID             int32 `json:"id"`
}

type SumJournalBalanceByAccountRow struct {
	AccountID   int32       `json:"account_id"`
	AccountCode string      `json:"account_code"`
	AccountName string      `json:"account_name"`
	TotalDebit  interface{} `json:"total_debit"`
	TotalCredit interface{} `json:"total_credit"`
	NetBalance  int32       `json:"net_balance"`
}

// AR aging / balance checks per account
func (q *Queries) SumJournalBalanceByAccount(ctx context.Context, arg SumJournalBalanceByAccountParams) (SumJournalBalanceByAccountRow, error) {
	row := q.db.QueryRow(ctx, sumJournalBalanceByAccount, arg.OrganizationID, arg.ID)
	var i SumJournalBalanceByAccountRow
	err := row.Scan(
		&i.AccountID,
		&i.AccountCode,
		&i.AccountName,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.NetBalance,
	)
	return i, err
}
