// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_categories.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuCategory = `-- name: CreateMenuCategory :one
INSERT INTO menu_categories (
    store_id, parent_category_id, name, code, description, category_level, display_order, icon, image_url, is_active, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, store_id, parent_category_id, name, code, description, category_level, display_order, icon, image_url, is_active, metadata, created_at, updated_at
`

type CreateMenuCategoryParams struct {
	StoreID          int32       `json:"store_id"`
	ParentCategoryID pgtype.Int4 `json:"parent_category_id"`
	Name             string      `json:"name"`
	Code             string      `json:"code"`
	Description      pgtype.Text `json:"description"`
	CategoryLevel    pgtype.Int4 `json:"category_level"`
	DisplayOrder     pgtype.Int4 `json:"display_order"`
	Icon             pgtype.Text `json:"icon"`
	ImageUrl         pgtype.Text `json:"image_url"`
	IsActive         pgtype.Bool `json:"is_active"`
	Metadata         []byte      `json:"metadata"`
}

func (q *Queries) CreateMenuCategory(ctx context.Context, arg CreateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, createMenuCategory,
		arg.StoreID,
		arg.ParentCategoryID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.CategoryLevel,
		arg.DisplayOrder,
		arg.Icon,
		arg.ImageUrl,
		arg.IsActive,
		arg.Metadata,
	)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ParentCategoryID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CategoryLevel,
		&i.DisplayOrder,
		&i.Icon,
		&i.ImageUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenuCategory = `-- name: DeleteMenuCategory :exec
DELETE FROM menu_categories
WHERE id = $1
`

func (q *Queries) DeleteMenuCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenuCategory, id)
	return err
}

const getMenuCategory = `-- name: GetMenuCategory :one

SELECT id, store_id, parent_category_id, name, code, description, category_level, display_order, icon, image_url, is_active, metadata, created_at, updated_at FROM menu_categories
WHERE id = $1 LIMIT 1
`

// menu_categories.sql
func (q *Queries) GetMenuCategory(ctx context.Context, id int32) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, getMenuCategory, id)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ParentCategoryID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CategoryLevel,
		&i.DisplayOrder,
		&i.Icon,
		&i.ImageUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenuCategories = `-- name: ListMenuCategories :many
SELECT id, store_id, parent_category_id, name, code, description, category_level, display_order, icon, image_url, is_active, metadata, created_at, updated_at FROM menu_categories
WHERE store_id = $1
ORDER BY display_order, name
`

func (q *Queries) ListMenuCategories(ctx context.Context, storeID int32) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategories, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ParentCategoryID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CategoryLevel,
			&i.DisplayOrder,
			&i.Icon,
			&i.ImageUrl,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuCategory = `-- name: UpdateMenuCategory :one
UPDATE menu_categories
SET
    parent_category_id = $2,
    name = $3,
    code = $4,
    description = $5,
    category_level = $6,
    display_order = $7,
    icon = $8,
    image_url = $9,
    is_active = $10,
    metadata = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, store_id, parent_category_id, name, code, description, category_level, display_order, icon, image_url, is_active, metadata, created_at, updated_at
`

type UpdateMenuCategoryParams struct {
	ID               int32       `json:"id"`
	ParentCategoryID pgtype.Int4 `json:"parent_category_id"`
	Name             string      `json:"name"`
	Code             string      `json:"code"`
	Description      pgtype.Text `json:"description"`
	CategoryLevel    pgtype.Int4 `json:"category_level"`
	DisplayOrder     pgtype.Int4 `json:"display_order"`
	Icon             pgtype.Text `json:"icon"`
	ImageUrl         pgtype.Text `json:"image_url"`
	IsActive         pgtype.Bool `json:"is_active"`
	Metadata         []byte      `json:"metadata"`
}

func (q *Queries) UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, updateMenuCategory,
		arg.ID,
		arg.ParentCategoryID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.CategoryLevel,
		arg.DisplayOrder,
		arg.Icon,
		arg.ImageUrl,
		arg.IsActive,
		arg.Metadata,
	)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ParentCategoryID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CategoryLevel,
		&i.DisplayOrder,
		&i.Icon,
		&i.ImageUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
