// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_item_modifiers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuItemModifier = `-- name: CreateMenuItemModifier :one
INSERT INTO menu_item_modifiers (
    menu_item_id, modifier_name, modifier_type, price_adjustment, is_active, display_order, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, menu_item_id, modifier_name, modifier_type, price_adjustment, is_active, display_order, metadata, created_at
`

type CreateMenuItemModifierParams struct {
	MenuItemID      int32          `json:"menu_item_id"`
	ModifierName    string         `json:"modifier_name"`
	ModifierType    string         `json:"modifier_type"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	IsActive        pgtype.Bool    `json:"is_active"`
	DisplayOrder    pgtype.Int4    `json:"display_order"`
	Metadata        []byte         `json:"metadata"`
}

func (q *Queries) CreateMenuItemModifier(ctx context.Context, arg CreateMenuItemModifierParams) (MenuItemModifier, error) {
	row := q.db.QueryRow(ctx, createMenuItemModifier,
		arg.MenuItemID,
		arg.ModifierName,
		arg.ModifierType,
		arg.PriceAdjustment,
		arg.IsActive,
		arg.DisplayOrder,
		arg.Metadata,
	)
	var i MenuItemModifier
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.ModifierName,
		&i.ModifierType,
		&i.PriceAdjustment,
		&i.IsActive,
		&i.DisplayOrder,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMenuItemModifier = `-- name: DeleteMenuItemModifier :exec
DELETE FROM menu_item_modifiers
WHERE id = $1
`

func (q *Queries) DeleteMenuItemModifier(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenuItemModifier, id)
	return err
}

const getMenuItemModifier = `-- name: GetMenuItemModifier :one

SELECT id, menu_item_id, modifier_name, modifier_type, price_adjustment, is_active, display_order, metadata, created_at FROM menu_item_modifiers
WHERE id = $1 LIMIT 1
`

// menu_item_modifiers.sql
func (q *Queries) GetMenuItemModifier(ctx context.Context, id int32) (MenuItemModifier, error) {
	row := q.db.QueryRow(ctx, getMenuItemModifier, id)
	var i MenuItemModifier
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.ModifierName,
		&i.ModifierType,
		&i.PriceAdjustment,
		&i.IsActive,
		&i.DisplayOrder,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listMenuItemModifiers = `-- name: ListMenuItemModifiers :many
SELECT id, menu_item_id, modifier_name, modifier_type, price_adjustment, is_active, display_order, metadata, created_at FROM menu_item_modifiers
WHERE menu_item_id = $1
ORDER BY display_order
`

func (q *Queries) ListMenuItemModifiers(ctx context.Context, menuItemID int32) ([]MenuItemModifier, error) {
	rows, err := q.db.Query(ctx, listMenuItemModifiers, menuItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItemModifier
	for rows.Next() {
		var i MenuItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.ModifierName,
			&i.ModifierType,
			&i.PriceAdjustment,
			&i.IsActive,
			&i.DisplayOrder,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItemModifier = `-- name: UpdateMenuItemModifier :one
UPDATE menu_item_modifiers
SET
    modifier_name = $2,
    modifier_type = $3,
    price_adjustment = $4,
    is_active = $5,
    display_order = $6,
    metadata = $7
WHERE id = $1
RETURNING id, menu_item_id, modifier_name, modifier_type, price_adjustment, is_active, display_order, metadata, created_at
`

type UpdateMenuItemModifierParams struct {
	ID              int32          `json:"id"`
	ModifierName    string         `json:"modifier_name"`
	ModifierType    string         `json:"modifier_type"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	IsActive        pgtype.Bool    `json:"is_active"`
	DisplayOrder    pgtype.Int4    `json:"display_order"`
	Metadata        []byte         `json:"metadata"`
}

func (q *Queries) UpdateMenuItemModifier(ctx context.Context, arg UpdateMenuItemModifierParams) (MenuItemModifier, error) {
	row := q.db.QueryRow(ctx, updateMenuItemModifier,
		arg.ID,
		arg.ModifierName,
		arg.ModifierType,
		arg.PriceAdjustment,
		arg.IsActive,
		arg.DisplayOrder,
		arg.Metadata,
	)
	var i MenuItemModifier
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.ModifierName,
		&i.ModifierType,
		&i.PriceAdjustment,
		&i.IsActive,
		&i.DisplayOrder,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
