// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_categories_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaxCategory = `-- name: CreateTaxCategory :one
INSERT INTO tax_categories (
    name,
    code,
    tax_rate,
    is_inclusive,
    is_active,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at
`

type CreateTaxCategoryParams struct {
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	TaxRate     pgtype.Numeric `json:"tax_rate"`
	IsInclusive pgtype.Bool    `json:"is_inclusive"`
	IsActive    pgtype.Bool    `json:"is_active"`
	Metadata    []byte         `json:"metadata"`
}

func (q *Queries) CreateTaxCategory(ctx context.Context, arg CreateTaxCategoryParams) (TaxCategory, error) {
	row := q.db.QueryRow(ctx, createTaxCategory,
		arg.Name,
		arg.Code,
		arg.TaxRate,
		arg.IsInclusive,
		arg.IsActive,
		arg.Metadata,
	)
	var i TaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.TaxRate,
		&i.IsInclusive,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaxCategory = `-- name: DeleteTaxCategory :exec
DELETE FROM tax_categories
WHERE id = $1
`

func (q *Queries) DeleteTaxCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTaxCategory, id)
	return err
}

const getTaxCategory = `-- name: GetTaxCategory :one
SELECT id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at FROM tax_categories
WHERE id = $1
`

func (q *Queries) GetTaxCategory(ctx context.Context, id int32) (TaxCategory, error) {
	row := q.db.QueryRow(ctx, getTaxCategory, id)
	var i TaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.TaxRate,
		&i.IsInclusive,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTaxCategoryByCode = `-- name: GetTaxCategoryByCode :one
SELECT id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at FROM tax_categories
WHERE code = $1
`

func (q *Queries) GetTaxCategoryByCode(ctx context.Context, code string) (TaxCategory, error) {
	row := q.db.QueryRow(ctx, getTaxCategoryByCode, code)
	var i TaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.TaxRate,
		&i.IsInclusive,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveTaxCategories = `-- name: ListActiveTaxCategories :many
SELECT id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at FROM tax_categories
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveTaxCategories(ctx context.Context) ([]TaxCategory, error) {
	rows, err := q.db.Query(ctx, listActiveTaxCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxCategory
	for rows.Next() {
		var i TaxCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.TaxRate,
			&i.IsInclusive,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxCategories = `-- name: ListTaxCategories :many
SELECT id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at FROM tax_categories
ORDER BY name
`

func (q *Queries) ListTaxCategories(ctx context.Context) ([]TaxCategory, error) {
	rows, err := q.db.Query(ctx, listTaxCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxCategory
	for rows.Next() {
		var i TaxCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.TaxRate,
			&i.IsInclusive,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTaxCategoryActive = `-- name: ToggleTaxCategoryActive :one
UPDATE tax_categories
SET is_active = $2
WHERE id = $1
RETURNING id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at
`

type ToggleTaxCategoryActiveParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) ToggleTaxCategoryActive(ctx context.Context, arg ToggleTaxCategoryActiveParams) (TaxCategory, error) {
	row := q.db.QueryRow(ctx, toggleTaxCategoryActive, arg.ID, arg.IsActive)
	var i TaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.TaxRate,
		&i.IsInclusive,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaxCategory = `-- name: UpdateTaxCategory :one
UPDATE tax_categories
SET 
    name = $2,
    tax_rate = $3,
    is_inclusive = $4,
    is_active = $5,
    metadata = $6
WHERE id = $1
RETURNING id, name, code, tax_rate, is_inclusive, is_active, metadata, created_at
`

type UpdateTaxCategoryParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	TaxRate     pgtype.Numeric `json:"tax_rate"`
	IsInclusive pgtype.Bool    `json:"is_inclusive"`
	IsActive    pgtype.Bool    `json:"is_active"`
	Metadata    []byte         `json:"metadata"`
}

func (q *Queries) UpdateTaxCategory(ctx context.Context, arg UpdateTaxCategoryParams) (TaxCategory, error) {
	row := q.db.QueryRow(ctx, updateTaxCategory,
		arg.ID,
		arg.Name,
		arg.TaxRate,
		arg.IsInclusive,
		arg.IsActive,
		arg.Metadata,
	)
	var i TaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.TaxRate,
		&i.IsInclusive,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
