// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer_requests.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const callApproveTransferRequest = `-- name: CallApproveTransferRequest :one
SELECT success::boolean AS success, message::text AS message FROM fn_approve_transfer_request($1, $2)
`

type CallApproveTransferRequestParams struct {
	PTransferRequestID int32 `json:"p_transfer_request_id"`
	PApprovedBy        int32 `json:"p_approved_by"`
}

type CallApproveTransferRequestRow struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (q *Queries) CallApproveTransferRequest(ctx context.Context, arg CallApproveTransferRequestParams) (CallApproveTransferRequestRow, error) {
	row := q.db.QueryRow(ctx, callApproveTransferRequest, arg.PTransferRequestID, arg.PApprovedBy)
	var i CallApproveTransferRequestRow
	err := row.Scan(&i.Success, &i.Message)
	return i, err
}

const callReceiveTransferRequest = `-- name: CallReceiveTransferRequest :one
SELECT success::boolean AS success, message::text AS message FROM fn_receive_transfer_request($1, $2)
`

type CallReceiveTransferRequestParams struct {
	PTransferRequestID int32 `json:"p_transfer_request_id"`
	PReceivedBy        int32 `json:"p_received_by"`
}

type CallReceiveTransferRequestRow struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (q *Queries) CallReceiveTransferRequest(ctx context.Context, arg CallReceiveTransferRequestParams) (CallReceiveTransferRequestRow, error) {
	row := q.db.QueryRow(ctx, callReceiveTransferRequest, arg.PTransferRequestID, arg.PReceivedBy)
	var i CallReceiveTransferRequestRow
	err := row.Scan(&i.Success, &i.Message)
	return i, err
}

const callShipTransferRequest = `-- name: CallShipTransferRequest :one
SELECT success::boolean AS success, message::text AS message FROM fn_ship_transfer_request($1, $2)
`

type CallShipTransferRequestParams struct {
	PTransferRequestID int32 `json:"p_transfer_request_id"`
	PShippedBy         int32 `json:"p_shipped_by"`
}

type CallShipTransferRequestRow struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (q *Queries) CallShipTransferRequest(ctx context.Context, arg CallShipTransferRequestParams) (CallShipTransferRequestRow, error) {
	row := q.db.QueryRow(ctx, callShipTransferRequest, arg.PTransferRequestID, arg.PShippedBy)
	var i CallShipTransferRequestRow
	err := row.Scan(&i.Success, &i.Message)
	return i, err
}

const createTransferRequest = `-- name: CreateTransferRequest :one

INSERT INTO transfer_requests (
    organization_id,
    transfer_number,
    from_store_id,
    to_store_id,
    status,
    requested_by,
    request_date,
    expected_delivery_date,
    notes,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, organization_id, transfer_number, from_store_id, to_store_id, status, requested_by, approved_by, shipped_by, received_by, request_date, expected_delivery_date, shipped_at, received_at, notes, metadata, created_at, updated_at
`

type CreateTransferRequestParams struct {
	OrganizationID       int32            `json:"organization_id"`
	TransferNumber       string           `json:"transfer_number"`
	FromStoreID          int32            `json:"from_store_id"`
	ToStoreID            int32            `json:"to_store_id"`
	Status               string           `json:"status"`
	RequestedBy          pgtype.Int4      `json:"requested_by"`
	RequestDate          pgtype.Timestamp `json:"request_date"`
	ExpectedDeliveryDate pgtype.Date      `json:"expected_delivery_date"`
	Notes                pgtype.Text      `json:"notes"`
	Metadata             json.RawMessage  `json:"metadata"`
}

// =====================================================
// TRANSFER REQUESTS QUERIES
// =====================================================
func (q *Queries) CreateTransferRequest(ctx context.Context, arg CreateTransferRequestParams) (TransferRequest, error) {
	row := q.db.QueryRow(ctx, createTransferRequest,
		arg.OrganizationID,
		arg.TransferNumber,
		arg.FromStoreID,
		arg.ToStoreID,
		arg.Status,
		arg.RequestedBy,
		arg.RequestDate,
		arg.ExpectedDeliveryDate,
		arg.Notes,
		arg.Metadata,
	)
	var i TransferRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferNumber,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ShippedBy,
		&i.ReceivedBy,
		&i.RequestDate,
		&i.ExpectedDeliveryDate,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransferRequestItem = `-- name: CreateTransferRequestItem :one
INSERT INTO transfer_request_items (
    transfer_request_id,
    product_id,
    product_variant_id,
    from_location_id,
    to_location_id,
    requested_quantity,
    approved_quantity,
    shipped_quantity,
    received_quantity,
    uom_id,
    batch_number,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, transfer_request_id, product_id, product_variant_id, from_location_id, to_location_id, requested_quantity, approved_quantity, shipped_quantity, received_quantity, uom_id, batch_number, notes, created_at
`

type CreateTransferRequestItemParams struct {
	TransferRequestID int32          `json:"transfer_request_id"`
	ProductID         int32          `json:"product_id"`
	ProductVariantID  pgtype.Int4    `json:"product_variant_id"`
	FromLocationID    pgtype.Int4    `json:"from_location_id"`
	ToLocationID      pgtype.Int4    `json:"to_location_id"`
	RequestedQuantity pgtype.Numeric `json:"requested_quantity"`
	ApprovedQuantity  pgtype.Numeric `json:"approved_quantity"`
	ShippedQuantity   pgtype.Numeric `json:"shipped_quantity"`
	ReceivedQuantity  pgtype.Numeric `json:"received_quantity"`
	UomID             pgtype.Int4    `json:"uom_id"`
	BatchNumber       pgtype.Text    `json:"batch_number"`
	Notes             pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateTransferRequestItem(ctx context.Context, arg CreateTransferRequestItemParams) (TransferRequestItem, error) {
	row := q.db.QueryRow(ctx, createTransferRequestItem,
		arg.TransferRequestID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.RequestedQuantity,
		arg.ApprovedQuantity,
		arg.ShippedQuantity,
		arg.ReceivedQuantity,
		arg.UomID,
		arg.BatchNumber,
		arg.Notes,
	)
	var i TransferRequestItem
	err := row.Scan(
		&i.ID,
		&i.TransferRequestID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.RequestedQuantity,
		&i.ApprovedQuantity,
		&i.ShippedQuantity,
		&i.ReceivedQuantity,
		&i.UomID,
		&i.BatchNumber,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getTransferRequest = `-- name: GetTransferRequest :one
SELECT id, organization_id, transfer_number, from_store_id, to_store_id, status, requested_by, approved_by, shipped_by, received_by, request_date, expected_delivery_date, shipped_at, received_at, notes, metadata, created_at, updated_at FROM transfer_requests WHERE id = $1
`

func (q *Queries) GetTransferRequest(ctx context.Context, id int32) (TransferRequest, error) {
	row := q.db.QueryRow(ctx, getTransferRequest, id)
	var i TransferRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferNumber,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ShippedBy,
		&i.ReceivedBy,
		&i.RequestDate,
		&i.ExpectedDeliveryDate,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransferRequestWithDetails = `-- name: GetTransferRequestWithDetails :one
SELECT 
    tr.id, tr.organization_id, tr.transfer_number, tr.from_store_id, tr.to_store_id, tr.status, tr.requested_by, tr.approved_by, tr.shipped_by, tr.received_by, tr.request_date, tr.expected_delivery_date, tr.shipped_at, tr.received_at, tr.notes, tr.metadata, tr.created_at, tr.updated_at,
    fs.name AS from_store_name,
    ts.name AS to_store_name,
    req_u.username AS requested_by_name,
    app_u.username AS approved_by_name
FROM transfer_requests tr
LEFT JOIN stores fs ON tr.from_store_id = fs.id
LEFT JOIN stores ts ON tr.to_store_id = ts.id
LEFT JOIN users req_u ON tr.requested_by = req_u.id
LEFT JOIN users app_u ON tr.approved_by = app_u.id
WHERE tr.id = $1
`

type GetTransferRequestWithDetailsRow struct {
	ID                   int32            `json:"id"`
	OrganizationID       int32            `json:"organization_id"`
	TransferNumber       string           `json:"transfer_number"`
	FromStoreID          int32            `json:"from_store_id"`
	ToStoreID            int32            `json:"to_store_id"`
	Status               string           `json:"status"`
	RequestedBy          pgtype.Int4      `json:"requested_by"`
	ApprovedBy           pgtype.Int4      `json:"approved_by"`
	ShippedBy            pgtype.Int4      `json:"shipped_by"`
	ReceivedBy           pgtype.Int4      `json:"received_by"`
	RequestDate          pgtype.Timestamp `json:"request_date"`
	ExpectedDeliveryDate pgtype.Date      `json:"expected_delivery_date"`
	ShippedAt            pgtype.Timestamp `json:"shipped_at"`
	ReceivedAt           pgtype.Timestamp `json:"received_at"`
	Notes                pgtype.Text      `json:"notes"`
	Metadata             json.RawMessage  `json:"metadata"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	FromStoreName        pgtype.Text      `json:"from_store_name"`
	ToStoreName          pgtype.Text      `json:"to_store_name"`
	RequestedByName      pgtype.Text      `json:"requested_by_name"`
	ApprovedByName       pgtype.Text      `json:"approved_by_name"`
}

func (q *Queries) GetTransferRequestWithDetails(ctx context.Context, id int32) (GetTransferRequestWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getTransferRequestWithDetails, id)
	var i GetTransferRequestWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferNumber,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ShippedBy,
		&i.ReceivedBy,
		&i.RequestDate,
		&i.ExpectedDeliveryDate,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FromStoreName,
		&i.ToStoreName,
		&i.RequestedByName,
		&i.ApprovedByName,
	)
	return i, err
}

const listTransferRequestItems = `-- name: ListTransferRequestItems :many
SELECT 
    tri.id, tri.transfer_request_id, tri.product_id, tri.product_variant_id, tri.from_location_id, tri.to_location_id, tri.requested_quantity, tri.approved_quantity, tri.shipped_quantity, tri.received_quantity, tri.uom_id, tri.batch_number, tri.notes, tri.created_at,
    p.name AS product_name,
    p.sku AS product_sku,
    uom.name AS uom_name
FROM transfer_request_items tri
JOIN products p ON tri.product_id = p.id
LEFT JOIN units_of_measure uom ON tri.uom_id = uom.id
WHERE tri.transfer_request_id = $1
`

type ListTransferRequestItemsRow struct {
	ID                int32            `json:"id"`
	TransferRequestID int32            `json:"transfer_request_id"`
	ProductID         int32            `json:"product_id"`
	ProductVariantID  pgtype.Int4      `json:"product_variant_id"`
	FromLocationID    pgtype.Int4      `json:"from_location_id"`
	ToLocationID      pgtype.Int4      `json:"to_location_id"`
	RequestedQuantity pgtype.Numeric   `json:"requested_quantity"`
	ApprovedQuantity  pgtype.Numeric   `json:"approved_quantity"`
	ShippedQuantity   pgtype.Numeric   `json:"shipped_quantity"`
	ReceivedQuantity  pgtype.Numeric   `json:"received_quantity"`
	UomID             pgtype.Int4      `json:"uom_id"`
	BatchNumber       pgtype.Text      `json:"batch_number"`
	Notes             pgtype.Text      `json:"notes"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	ProductName       string           `json:"product_name"`
	ProductSku        string           `json:"product_sku"`
	UomName           pgtype.Text      `json:"uom_name"`
}

func (q *Queries) ListTransferRequestItems(ctx context.Context, transferRequestID int32) ([]ListTransferRequestItemsRow, error) {
	rows, err := q.db.Query(ctx, listTransferRequestItems, transferRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferRequestItemsRow
	for rows.Next() {
		var i ListTransferRequestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferRequestID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.RequestedQuantity,
			&i.ApprovedQuantity,
			&i.ShippedQuantity,
			&i.ReceivedQuantity,
			&i.UomID,
			&i.BatchNumber,
			&i.Notes,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductSku,
			&i.UomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferRequestsByOrganization = `-- name: ListTransferRequestsByOrganization :many
SELECT 
    tr.id, tr.organization_id, tr.transfer_number, tr.from_store_id, tr.to_store_id, tr.status, tr.requested_by, tr.approved_by, tr.shipped_by, tr.received_by, tr.request_date, tr.expected_delivery_date, tr.shipped_at, tr.received_at, tr.notes, tr.metadata, tr.created_at, tr.updated_at,
    fs.name AS from_store_name,
    ts.name AS to_store_name
FROM transfer_requests tr
LEFT JOIN stores fs ON tr.from_store_id = fs.id
LEFT JOIN stores ts ON tr.to_store_id = ts.id
WHERE tr.organization_id = $1
ORDER BY tr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransferRequestsByOrganizationParams struct {
	OrganizationID int32 `json:"organization_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

type ListTransferRequestsByOrganizationRow struct {
	ID                   int32            `json:"id"`
	OrganizationID       int32            `json:"organization_id"`
	TransferNumber       string           `json:"transfer_number"`
	FromStoreID          int32            `json:"from_store_id"`
	ToStoreID            int32            `json:"to_store_id"`
	Status               string           `json:"status"`
	RequestedBy          pgtype.Int4      `json:"requested_by"`
	ApprovedBy           pgtype.Int4      `json:"approved_by"`
	ShippedBy            pgtype.Int4      `json:"shipped_by"`
	ReceivedBy           pgtype.Int4      `json:"received_by"`
	RequestDate          pgtype.Timestamp `json:"request_date"`
	ExpectedDeliveryDate pgtype.Date      `json:"expected_delivery_date"`
	ShippedAt            pgtype.Timestamp `json:"shipped_at"`
	ReceivedAt           pgtype.Timestamp `json:"received_at"`
	Notes                pgtype.Text      `json:"notes"`
	Metadata             json.RawMessage  `json:"metadata"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	FromStoreName        pgtype.Text      `json:"from_store_name"`
	ToStoreName          pgtype.Text      `json:"to_store_name"`
}

func (q *Queries) ListTransferRequestsByOrganization(ctx context.Context, arg ListTransferRequestsByOrganizationParams) ([]ListTransferRequestsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listTransferRequestsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferRequestsByOrganizationRow
	for rows.Next() {
		var i ListTransferRequestsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TransferNumber,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ShippedBy,
			&i.ReceivedBy,
			&i.RequestDate,
			&i.ExpectedDeliveryDate,
			&i.ShippedAt,
			&i.ReceivedAt,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromStoreName,
			&i.ToStoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferRequestsByStore = `-- name: ListTransferRequestsByStore :many
SELECT 
    tr.id, tr.organization_id, tr.transfer_number, tr.from_store_id, tr.to_store_id, tr.status, tr.requested_by, tr.approved_by, tr.shipped_by, tr.received_by, tr.request_date, tr.expected_delivery_date, tr.shipped_at, tr.received_at, tr.notes, tr.metadata, tr.created_at, tr.updated_at,
    fs.name AS from_store_name,
    ts.name AS to_store_name
FROM transfer_requests tr
LEFT JOIN stores fs ON tr.from_store_id = fs.id
LEFT JOIN stores ts ON tr.to_store_id = ts.id
WHERE tr.from_store_id = $1 OR tr.to_store_id = $1
ORDER BY tr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransferRequestsByStoreParams struct {
	FromStoreID int32 `json:"from_store_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type ListTransferRequestsByStoreRow struct {
	ID                   int32            `json:"id"`
	OrganizationID       int32            `json:"organization_id"`
	TransferNumber       string           `json:"transfer_number"`
	FromStoreID          int32            `json:"from_store_id"`
	ToStoreID            int32            `json:"to_store_id"`
	Status               string           `json:"status"`
	RequestedBy          pgtype.Int4      `json:"requested_by"`
	ApprovedBy           pgtype.Int4      `json:"approved_by"`
	ShippedBy            pgtype.Int4      `json:"shipped_by"`
	ReceivedBy           pgtype.Int4      `json:"received_by"`
	RequestDate          pgtype.Timestamp `json:"request_date"`
	ExpectedDeliveryDate pgtype.Date      `json:"expected_delivery_date"`
	ShippedAt            pgtype.Timestamp `json:"shipped_at"`
	ReceivedAt           pgtype.Timestamp `json:"received_at"`
	Notes                pgtype.Text      `json:"notes"`
	Metadata             json.RawMessage  `json:"metadata"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	FromStoreName        pgtype.Text      `json:"from_store_name"`
	ToStoreName          pgtype.Text      `json:"to_store_name"`
}

func (q *Queries) ListTransferRequestsByStore(ctx context.Context, arg ListTransferRequestsByStoreParams) ([]ListTransferRequestsByStoreRow, error) {
	rows, err := q.db.Query(ctx, listTransferRequestsByStore, arg.FromStoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferRequestsByStoreRow
	for rows.Next() {
		var i ListTransferRequestsByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TransferNumber,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ShippedBy,
			&i.ReceivedBy,
			&i.RequestDate,
			&i.ExpectedDeliveryDate,
			&i.ShippedAt,
			&i.ReceivedAt,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromStoreName,
			&i.ToStoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferRequestStatus = `-- name: UpdateTransferRequestStatus :one
UPDATE transfer_requests
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, transfer_number, from_store_id, to_store_id, status, requested_by, approved_by, shipped_by, received_by, request_date, expected_delivery_date, shipped_at, received_at, notes, metadata, created_at, updated_at
`

type UpdateTransferRequestStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTransferRequestStatus(ctx context.Context, arg UpdateTransferRequestStatusParams) (TransferRequest, error) {
	row := q.db.QueryRow(ctx, updateTransferRequestStatus, arg.ID, arg.Status)
	var i TransferRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferNumber,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ShippedBy,
		&i.ReceivedBy,
		&i.RequestDate,
		&i.ExpectedDeliveryDate,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
