// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zatca.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createZatcaDeviceConfig = `-- name: CreateZatcaDeviceConfig :one
INSERT INTO zatca_device_configs (
    organization_id, store_id, pos_terminal_id,
    device_serial, device_type,
    csr_pem, private_key_pem,
    compliance_csid, production_csid, csid_expiry,
    zatca_env, is_active, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at
`

type CreateZatcaDeviceConfigParams struct {
	OrganizationID int32              `json:"organization_id"`
	StoreID        pgtype.Int4        `json:"store_id"`
	PosTerminalID  pgtype.Int4        `json:"pos_terminal_id"`
	DeviceSerial   string             `json:"device_serial"`
	DeviceType     string             `json:"device_type"`
	CsrPem         pgtype.Text        `json:"csr_pem"`
	PrivateKeyPem  string             `json:"private_key_pem"`
	ComplianceCsid pgtype.Text        `json:"compliance_csid"`
	ProductionCsid pgtype.Text        `json:"production_csid"`
	CsidExpiry     pgtype.Timestamptz `json:"csid_expiry"`
	ZatcaEnv       pgtype.Text        `json:"zatca_env"`
	IsActive       pgtype.Bool        `json:"is_active"`
	Metadata       json.RawMessage    `json:"metadata"`
}

func (q *Queries) CreateZatcaDeviceConfig(ctx context.Context, arg CreateZatcaDeviceConfigParams) (ZatcaDeviceConfig, error) {
	row := q.db.QueryRow(ctx, createZatcaDeviceConfig,
		arg.OrganizationID,
		arg.StoreID,
		arg.PosTerminalID,
		arg.DeviceSerial,
		arg.DeviceType,
		arg.CsrPem,
		arg.PrivateKeyPem,
		arg.ComplianceCsid,
		arg.ProductionCsid,
		arg.CsidExpiry,
		arg.ZatcaEnv,
		arg.IsActive,
		arg.Metadata,
	)
	var i ZatcaDeviceConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.PosTerminalID,
		&i.DeviceSerial,
		&i.DeviceType,
		&i.CsrPem,
		&i.PrivateKeyPem,
		&i.ComplianceCsid,
		&i.ProductionCsid,
		&i.CsidExpiry,
		&i.ZatcaEnv,
		&i.IsActive,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCloudDevice = `-- name: GetActiveCloudDevice :one
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE organization_id = $1
  AND device_type = 'cloud'
  AND is_active = true
  AND is_revoked = false
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCloudDevice(ctx context.Context, organizationID int32) (ZatcaDeviceConfig, error) {
	row := q.db.QueryRow(ctx, getActiveCloudDevice, organizationID)
	var i ZatcaDeviceConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.PosTerminalID,
		&i.DeviceSerial,
		&i.DeviceType,
		&i.CsrPem,
		&i.PrivateKeyPem,
		&i.ComplianceCsid,
		&i.ProductionCsid,
		&i.CsidExpiry,
		&i.ZatcaEnv,
		&i.IsActive,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePosDevice = `-- name: GetActivePosDevice :one
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE organization_id = $1
  AND pos_terminal_id = $2
  AND device_type = 'pos'
  AND is_active = true
  AND is_revoked = false
ORDER BY created_at DESC
LIMIT 1
`

type GetActivePosDeviceParams struct {
	OrganizationID int32       `json:"organization_id"`
	PosTerminalID  pgtype.Int4 `json:"pos_terminal_id"`
}

func (q *Queries) GetActivePosDevice(ctx context.Context, arg GetActivePosDeviceParams) (ZatcaDeviceConfig, error) {
	row := q.db.QueryRow(ctx, getActivePosDevice, arg.OrganizationID, arg.PosTerminalID)
	var i ZatcaDeviceConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.PosTerminalID,
		&i.DeviceSerial,
		&i.DeviceType,
		&i.CsrPem,
		&i.PrivateKeyPem,
		&i.ComplianceCsid,
		&i.ProductionCsid,
		&i.CsidExpiry,
		&i.ZatcaEnv,
		&i.IsActive,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChainEntryByEntity = `-- name: GetChainEntryByEntity :one
SELECT id, entity_type, entity_id, device_config_id, organization_id, zatca_uuid, icv, pih, xml_hash, zatca_status, zatca_response, qr_code_base64, signed_xml, submitted_at, cleared_at, created_at, updated_at FROM zatca_document_chain
WHERE entity_type = $1 AND entity_id = $2
`

type GetChainEntryByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetChainEntryByEntity(ctx context.Context, arg GetChainEntryByEntityParams) (ZatcaDocumentChain, error) {
	row := q.db.QueryRow(ctx, getChainEntryByEntity, arg.EntityType, arg.EntityID)
	var i ZatcaDocumentChain
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.DeviceConfigID,
		&i.OrganizationID,
		&i.ZatcaUuid,
		&i.Icv,
		&i.Pih,
		&i.XmlHash,
		&i.ZatcaStatus,
		&i.ZatcaResponse,
		&i.QrCodeBase64,
		&i.SignedXml,
		&i.SubmittedAt,
		&i.ClearedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestChainEntry = `-- name: GetLatestChainEntry :one

SELECT id, entity_type, entity_id, device_config_id, organization_id, zatca_uuid, icv, pih, xml_hash, zatca_status, zatca_response, qr_code_base64, signed_xml, submitted_at, cleared_at, created_at, updated_at FROM zatca_document_chain
WHERE device_config_id = $1
ORDER BY icv DESC
LIMIT 1
`

// ZATCA Document Chain Queries
// ====================================
// Returns the most recent chain entry for a specific device (for PIH lookup)
func (q *Queries) GetLatestChainEntry(ctx context.Context, deviceConfigID int32) (ZatcaDocumentChain, error) {
	row := q.db.QueryRow(ctx, getLatestChainEntry, deviceConfigID)
	var i ZatcaDocumentChain
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.DeviceConfigID,
		&i.OrganizationID,
		&i.ZatcaUuid,
		&i.Icv,
		&i.Pih,
		&i.XmlHash,
		&i.ZatcaStatus,
		&i.ZatcaResponse,
		&i.QrCodeBase64,
		&i.SignedXml,
		&i.SubmittedAt,
		&i.ClearedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextICV = `-- name: GetNextICV :one
SELECT COALESCE(MAX(icv), 0) + 1 AS next_icv
FROM zatca_document_chain
WHERE device_config_id = $1
`

// Returns MAX(icv) + 1 for a device, or 1 if no entries exist
func (q *Queries) GetNextICV(ctx context.Context, deviceConfigID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextICV, deviceConfigID)
	var next_icv int32
	err := row.Scan(&next_icv)
	return next_icv, err
}

const getSyncWatermark = `-- name: GetSyncWatermark :one

SELECT id, entity_type, store_id, last_sync_at, metadata FROM sync_watermarks
WHERE entity_type = $1 AND store_id = $2
`

type GetSyncWatermarkParams struct {
	EntityType string      `json:"entity_type"`
	StoreID    pgtype.Int4 `json:"store_id"`
}

// Sync Watermark Queries
// ====================================
func (q *Queries) GetSyncWatermark(ctx context.Context, arg GetSyncWatermarkParams) (SyncWatermark, error) {
	row := q.db.QueryRow(ctx, getSyncWatermark, arg.EntityType, arg.StoreID)
	var i SyncWatermark
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.StoreID,
		&i.LastSyncAt,
		&i.Metadata,
	)
	return i, err
}

const getZatcaConfigsDelta = `-- name: GetZatcaConfigsDelta :many
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE store_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type GetZatcaConfigsDeltaParams struct {
	StoreID   pgtype.Int4      `json:"store_id"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// Delta-fetch: returns configs modified since a given timestamp for a store
func (q *Queries) GetZatcaConfigsDelta(ctx context.Context, arg GetZatcaConfigsDeltaParams) ([]ZatcaDeviceConfig, error) {
	rows, err := q.db.Query(ctx, getZatcaConfigsDelta, arg.StoreID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZatcaDeviceConfig
	for rows.Next() {
		var i ZatcaDeviceConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.PosTerminalID,
			&i.DeviceSerial,
			&i.DeviceType,
			&i.CsrPem,
			&i.PrivateKeyPem,
			&i.ComplianceCsid,
			&i.ProductionCsid,
			&i.CsidExpiry,
			&i.ZatcaEnv,
			&i.IsActive,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZatcaConfigsDeltaByOrg = `-- name: GetZatcaConfigsDeltaByOrg :many
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE organization_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type GetZatcaConfigsDeltaByOrgParams struct {
	OrganizationID int32            `json:"organization_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

// Delta-fetch by org: returns configs modified since a given timestamp
func (q *Queries) GetZatcaConfigsDeltaByOrg(ctx context.Context, arg GetZatcaConfigsDeltaByOrgParams) ([]ZatcaDeviceConfig, error) {
	rows, err := q.db.Query(ctx, getZatcaConfigsDeltaByOrg, arg.OrganizationID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZatcaDeviceConfig
	for rows.Next() {
		var i ZatcaDeviceConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.PosTerminalID,
			&i.DeviceSerial,
			&i.DeviceType,
			&i.CsrPem,
			&i.PrivateKeyPem,
			&i.ComplianceCsid,
			&i.ProductionCsid,
			&i.CsidExpiry,
			&i.ZatcaEnv,
			&i.IsActive,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZatcaDeviceConfig = `-- name: GetZatcaDeviceConfig :one

SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs WHERE id = $1
`

// ZATCA Device Configuration Queries
// ====================================
func (q *Queries) GetZatcaDeviceConfig(ctx context.Context, id int32) (ZatcaDeviceConfig, error) {
	row := q.db.QueryRow(ctx, getZatcaDeviceConfig, id)
	var i ZatcaDeviceConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.PosTerminalID,
		&i.DeviceSerial,
		&i.DeviceType,
		&i.CsrPem,
		&i.PrivateKeyPem,
		&i.ComplianceCsid,
		&i.ProductionCsid,
		&i.CsidExpiry,
		&i.ZatcaEnv,
		&i.IsActive,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getZatcaDeviceConfigBySerial = `-- name: GetZatcaDeviceConfigBySerial :one
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE organization_id = $1 AND device_serial = $2
`

type GetZatcaDeviceConfigBySerialParams struct {
	OrganizationID int32  `json:"organization_id"`
	DeviceSerial   string `json:"device_serial"`
}

func (q *Queries) GetZatcaDeviceConfigBySerial(ctx context.Context, arg GetZatcaDeviceConfigBySerialParams) (ZatcaDeviceConfig, error) {
	row := q.db.QueryRow(ctx, getZatcaDeviceConfigBySerial, arg.OrganizationID, arg.DeviceSerial)
	var i ZatcaDeviceConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.PosTerminalID,
		&i.DeviceSerial,
		&i.DeviceType,
		&i.CsrPem,
		&i.PrivateKeyPem,
		&i.ComplianceCsid,
		&i.ProductionCsid,
		&i.CsidExpiry,
		&i.ZatcaEnv,
		&i.IsActive,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChainEntry = `-- name: InsertChainEntry :one
INSERT INTO zatca_document_chain (
    entity_type, entity_id,
    device_config_id, organization_id,
    zatca_uuid, icv, pih, xml_hash,
    zatca_status, qr_code_base64, signed_xml
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, entity_type, entity_id, device_config_id, organization_id, zatca_uuid, icv, pih, xml_hash, zatca_status, zatca_response, qr_code_base64, signed_xml, submitted_at, cleared_at, created_at, updated_at
`

type InsertChainEntryParams struct {
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	DeviceConfigID int32              `json:"device_config_id"`
	OrganizationID int32              `json:"organization_id"`
	ZatcaUuid      uuid.UUID          `json:"zatca_uuid"`
	Icv            int64              `json:"icv"`
	Pih            string             `json:"pih"`
	XmlHash        string             `json:"xml_hash"`
	ZatcaStatus    NullZatcaDocStatus `json:"zatca_status"`
	QrCodeBase64   pgtype.Text        `json:"qr_code_base64"`
	SignedXml      pgtype.Text        `json:"signed_xml"`
}

func (q *Queries) InsertChainEntry(ctx context.Context, arg InsertChainEntryParams) (ZatcaDocumentChain, error) {
	row := q.db.QueryRow(ctx, insertChainEntry,
		arg.EntityType,
		arg.EntityID,
		arg.DeviceConfigID,
		arg.OrganizationID,
		arg.ZatcaUuid,
		arg.Icv,
		arg.Pih,
		arg.XmlHash,
		arg.ZatcaStatus,
		arg.QrCodeBase64,
		arg.SignedXml,
	)
	var i ZatcaDocumentChain
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.DeviceConfigID,
		&i.OrganizationID,
		&i.ZatcaUuid,
		&i.Icv,
		&i.Pih,
		&i.XmlHash,
		&i.ZatcaStatus,
		&i.ZatcaResponse,
		&i.QrCodeBase64,
		&i.SignedXml,
		&i.SubmittedAt,
		&i.ClearedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChainEntriesByDevice = `-- name: ListChainEntriesByDevice :many
SELECT id, entity_type, entity_id, device_config_id, organization_id, zatca_uuid, icv, pih, xml_hash, zatca_status, zatca_response, qr_code_base64, signed_xml, submitted_at, cleared_at, created_at, updated_at FROM zatca_document_chain
WHERE device_config_id = $1
ORDER BY icv DESC
LIMIT $2 OFFSET $3
`

type ListChainEntriesByDeviceParams struct {
	DeviceConfigID int32 `json:"device_config_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

func (q *Queries) ListChainEntriesByDevice(ctx context.Context, arg ListChainEntriesByDeviceParams) ([]ZatcaDocumentChain, error) {
	rows, err := q.db.Query(ctx, listChainEntriesByDevice, arg.DeviceConfigID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZatcaDocumentChain
	for rows.Next() {
		var i ZatcaDocumentChain
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.DeviceConfigID,
			&i.OrganizationID,
			&i.ZatcaUuid,
			&i.Icv,
			&i.Pih,
			&i.XmlHash,
			&i.ZatcaStatus,
			&i.ZatcaResponse,
			&i.QrCodeBase64,
			&i.SignedXml,
			&i.SubmittedAt,
			&i.ClearedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingChainEntries = `-- name: ListPendingChainEntries :many
SELECT id, entity_type, entity_id, device_config_id, organization_id, zatca_uuid, icv, pih, xml_hash, zatca_status, zatca_response, qr_code_base64, signed_xml, submitted_at, cleared_at, created_at, updated_at FROM zatca_document_chain
WHERE zatca_status IN ('pending', 'failed')
ORDER BY created_at ASC
LIMIT $1
`

// For reporting worker: entries awaiting submission to ZATCA
func (q *Queries) ListPendingChainEntries(ctx context.Context, limit int32) ([]ZatcaDocumentChain, error) {
	rows, err := q.db.Query(ctx, listPendingChainEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZatcaDocumentChain
	for rows.Next() {
		var i ZatcaDocumentChain
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.DeviceConfigID,
			&i.OrganizationID,
			&i.ZatcaUuid,
			&i.Icv,
			&i.Pih,
			&i.XmlHash,
			&i.ZatcaStatus,
			&i.ZatcaResponse,
			&i.QrCodeBase64,
			&i.SignedXml,
			&i.SubmittedAt,
			&i.ClearedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZatcaDeviceConfigsByOrg = `-- name: ListZatcaDeviceConfigsByOrg :many
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListZatcaDeviceConfigsByOrg(ctx context.Context, organizationID int32) ([]ZatcaDeviceConfig, error) {
	rows, err := q.db.Query(ctx, listZatcaDeviceConfigsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZatcaDeviceConfig
	for rows.Next() {
		var i ZatcaDeviceConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.PosTerminalID,
			&i.DeviceSerial,
			&i.DeviceType,
			&i.CsrPem,
			&i.PrivateKeyPem,
			&i.ComplianceCsid,
			&i.ProductionCsid,
			&i.CsidExpiry,
			&i.ZatcaEnv,
			&i.IsActive,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZatcaDeviceConfigsByStore = `-- name: ListZatcaDeviceConfigsByStore :many
SELECT id, organization_id, store_id, pos_terminal_id, device_serial, device_type, csr_pem, private_key_pem, compliance_csid, production_csid, csid_expiry, zatca_env, is_active, is_revoked, revoked_at, revoked_reason, metadata, created_at, updated_at FROM zatca_device_configs
WHERE store_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListZatcaDeviceConfigsByStore(ctx context.Context, storeID pgtype.Int4) ([]ZatcaDeviceConfig, error) {
	rows, err := q.db.Query(ctx, listZatcaDeviceConfigsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZatcaDeviceConfig
	for rows.Next() {
		var i ZatcaDeviceConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.PosTerminalID,
			&i.DeviceSerial,
			&i.DeviceType,
			&i.CsrPem,
			&i.PrivateKeyPem,
			&i.ComplianceCsid,
			&i.ProductionCsid,
			&i.CsidExpiry,
			&i.ZatcaEnv,
			&i.IsActive,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeZatcaDevice = `-- name: RevokeZatcaDevice :exec
UPDATE zatca_device_configs
SET is_revoked     = true,
    is_active      = false,
    revoked_at     = NOW(),
    revoked_reason = $2,
    updated_at     = NOW()
WHERE id = $1
`

type RevokeZatcaDeviceParams struct {
	ID            int32       `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeZatcaDevice(ctx context.Context, arg RevokeZatcaDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeZatcaDevice, arg.ID, arg.RevokedReason)
	return err
}

const updateChainEntryQRCode = `-- name: UpdateChainEntryQRCode :exec
UPDATE zatca_document_chain
SET qr_code_base64 = $2
WHERE id = $1
`

type UpdateChainEntryQRCodeParams struct {
	ID           int64       `json:"id"`
	QrCodeBase64 pgtype.Text `json:"qr_code_base64"`
}

func (q *Queries) UpdateChainEntryQRCode(ctx context.Context, arg UpdateChainEntryQRCodeParams) error {
	_, err := q.db.Exec(ctx, updateChainEntryQRCode, arg.ID, arg.QrCodeBase64)
	return err
}

const updateChainEntryStatus = `-- name: UpdateChainEntryStatus :exec
UPDATE zatca_document_chain
SET zatca_status   = $2,
    zatca_response = $3,
    submitted_at   = $4,
    cleared_at     = $5
WHERE id = $1
`

type UpdateChainEntryStatusParams struct {
	ID            int64              `json:"id"`
	ZatcaStatus   NullZatcaDocStatus `json:"zatca_status"`
	ZatcaResponse json.RawMessage    `json:"zatca_response"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	ClearedAt     pgtype.Timestamptz `json:"cleared_at"`
}

func (q *Queries) UpdateChainEntryStatus(ctx context.Context, arg UpdateChainEntryStatusParams) error {
	_, err := q.db.Exec(ctx, updateChainEntryStatus,
		arg.ID,
		arg.ZatcaStatus,
		arg.ZatcaResponse,
		arg.SubmittedAt,
		arg.ClearedAt,
	)
	return err
}

const updateZatcaDeviceCSID = `-- name: UpdateZatcaDeviceCSID :exec
UPDATE zatca_device_configs
SET compliance_csid = $2,
    production_csid = $3,
    csid_expiry     = $4,
    updated_at      = NOW()
WHERE id = $1
`

type UpdateZatcaDeviceCSIDParams struct {
	ID             int32              `json:"id"`
	ComplianceCsid pgtype.Text        `json:"compliance_csid"`
	ProductionCsid pgtype.Text        `json:"production_csid"`
	CsidExpiry     pgtype.Timestamptz `json:"csid_expiry"`
}

func (q *Queries) UpdateZatcaDeviceCSID(ctx context.Context, arg UpdateZatcaDeviceCSIDParams) error {
	_, err := q.db.Exec(ctx, updateZatcaDeviceCSID,
		arg.ID,
		arg.ComplianceCsid,
		arg.ProductionCsid,
		arg.CsidExpiry,
	)
	return err
}

const upsertSyncWatermark = `-- name: UpsertSyncWatermark :exec
INSERT INTO sync_watermarks (entity_type, store_id, last_sync_at)
VALUES ($1, $2, $3)
ON CONFLICT (entity_type, store_id) DO UPDATE
SET last_sync_at = EXCLUDED.last_sync_at
`

type UpsertSyncWatermarkParams struct {
	EntityType string      `json:"entity_type"`
	StoreID    pgtype.Int4 `json:"store_id"`
	LastSyncAt time.Time   `json:"last_sync_at"`
}

func (q *Queries) UpsertSyncWatermark(ctx context.Context, arg UpsertSyncWatermarkParams) error {
	_, err := q.db.Exec(ctx, upsertSyncWatermark, arg.EntityType, arg.StoreID, arg.LastSyncAt)
	return err
}
