// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cashiers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCashierWithLimits = `-- name: GetCashierWithLimits :one
SELECT 
    c.id,
    c.cashier_code,
    c.drawer_limit,
    c.discount_limit,
    c.is_active,
    u.first_name,
    u.last_name,
    u.email,
    s.name AS store_name
FROM cashiers c
JOIN users u ON c.user_id = u.id
JOIN stores s ON c.store_id = s.id
WHERE c.id = $1
`

type GetCashierWithLimitsRow struct {
	ID            int32          `json:"id"`
	CashierCode   string         `json:"cashier_code"`
	DrawerLimit   pgtype.Numeric `json:"drawer_limit"`
	DiscountLimit pgtype.Numeric `json:"discount_limit"`
	IsActive      pgtype.Bool    `json:"is_active"`
	FirstName     pgtype.Text    `json:"first_name"`
	LastName      pgtype.Text    `json:"last_name"`
	Email         string         `json:"email"`
	StoreName     string         `json:"store_name"`
}

func (q *Queries) GetCashierWithLimits(ctx context.Context, id int32) (GetCashierWithLimitsRow, error) {
	row := q.db.QueryRow(ctx, getCashierWithLimits, id)
	var i GetCashierWithLimitsRow
	err := row.Scan(
		&i.ID,
		&i.CashierCode,
		&i.DrawerLimit,
		&i.DiscountLimit,
		&i.IsActive,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.StoreName,
	)
	return i, err
}

const listActiveCashiersInStore = `-- name: ListActiveCashiersInStore :many
SELECT 
    c.id,
    c.cashier_code,
    u.first_name || ' ' || u.last_name AS full_name,
    c.discount_limit,
    c.drawer_limit,
    COUNT(cs.id) FILTER (WHERE cs.status = 'open') AS active_sessions
FROM cashiers c
JOIN users u ON c.user_id = u.id
LEFT JOIN cashier_sessions cs ON cs.cashier_id = c.id AND cs.status = 'open'
WHERE c.store_id = $1
  AND c.is_active = true
GROUP BY c.id, u.first_name, u.last_name
ORDER BY u.first_name
`

type ListActiveCashiersInStoreRow struct {
	ID             int32          `json:"id"`
	CashierCode    string         `json:"cashier_code"`
	FullName       interface{}    `json:"full_name"`
	DiscountLimit  pgtype.Numeric `json:"discount_limit"`
	DrawerLimit    pgtype.Numeric `json:"drawer_limit"`
	ActiveSessions int64          `json:"active_sessions"`
}

func (q *Queries) ListActiveCashiersInStore(ctx context.Context, storeID int32) ([]ListActiveCashiersInStoreRow, error) {
	rows, err := q.db.Query(ctx, listActiveCashiersInStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCashiersInStoreRow
	for rows.Next() {
		var i ListActiveCashiersInStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.CashierCode,
			&i.FullName,
			&i.DiscountLimit,
			&i.DrawerLimit,
			&i.ActiveSessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
