// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToMenu = `-- name: AssignPermissionToMenu :one

INSERT INTO menu_permissions (
    menu_id, permission_id, metadata
) VALUES (
    $1, $2, $3
) RETURNING id, menu_id, permission_id, metadata
`

type AssignPermissionToMenuParams struct {
	MenuID       int32  `json:"menu_id"`
	PermissionID int32  `json:"permission_id"`
	Metadata     []byte `json:"metadata"`
}

// =====================================================
// MENU PERMISSIONS
// =====================================================
func (q *Queries) AssignPermissionToMenu(ctx context.Context, arg AssignPermissionToMenuParams) (MenuPermission, error) {
	row := q.db.QueryRow(ctx, assignPermissionToMenu, arg.MenuID, arg.PermissionID, arg.Metadata)
	var i MenuPermission
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const assignPermissionToModule = `-- name: AssignPermissionToModule :one

INSERT INTO module_permissions (
    module_id, permission_id, metadata
) VALUES (
    $1, $2, $3
) RETURNING id, module_id, permission_id, metadata
`

type AssignPermissionToModuleParams struct {
	ModuleID     int32  `json:"module_id"`
	PermissionID int32  `json:"permission_id"`
	Metadata     []byte `json:"metadata"`
}

// =====================================================
// MODULE PERMISSIONS
// =====================================================
func (q *Queries) AssignPermissionToModule(ctx context.Context, arg AssignPermissionToModuleParams) (ModulePermission, error) {
	row := q.db.QueryRow(ctx, assignPermissionToModule, arg.ModuleID, arg.PermissionID, arg.Metadata)
	var i ModulePermission
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const assignPermissionToSubmenu = `-- name: AssignPermissionToSubmenu :one

INSERT INTO submenu_permissions (
    submenu_id, permission_id, metadata
) VALUES (
    $1, $2, $3
) RETURNING id, submenu_id, permission_id, metadata
`

type AssignPermissionToSubmenuParams struct {
	SubmenuID    int32  `json:"submenu_id"`
	PermissionID int32  `json:"permission_id"`
	Metadata     []byte `json:"metadata"`
}

// =====================================================
// SUBMENU PERMISSIONS
// =====================================================
func (q *Queries) AssignPermissionToSubmenu(ctx context.Context, arg AssignPermissionToSubmenuParams) (SubmenuPermission, error) {
	row := q.db.QueryRow(ctx, assignPermissionToSubmenu, arg.SubmenuID, arg.PermissionID, arg.Metadata)
	var i SubmenuPermission
	err := row.Scan(
		&i.ID,
		&i.SubmenuID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const checkUserHasPermission = `-- name: CheckUserHasPermission :one
SELECT EXISTS(
    SELECT 1 FROM permissions p
    INNER JOIN role_permissions rp ON p.id = rp.permission_id
    INNER JOIN user_roles ur ON rp.role_id = ur.role_id
    WHERE ur.user_id = $1 AND p.code = $2
) as has_permission
`

type CheckUserHasPermissionParams struct {
	UserID int32  `json:"user_id"`
	Code   string `json:"code"`
}

func (q *Queries) CheckUserHasPermission(ctx context.Context, arg CheckUserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasPermission, arg.UserID, arg.Code)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (
    name, code, description, metadata
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, code, description, metadata, created_at
`

type CreatePermissionParams struct {
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	Description pgtype.Text `json:"description"`
	Metadata    []byte      `json:"metadata"`
}

// =====================================================
// PERMISSIONS
// =====================================================
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Metadata,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getMenuPermissions = `-- name: GetMenuPermissions :many
SELECT p.id, p.name, p.code, p.description, p.metadata, p.created_at FROM permissions p
INNER JOIN menu_permissions mp ON p.id = mp.permission_id
WHERE mp.menu_id = $1
`

func (q *Queries) GetMenuPermissions(ctx context.Context, menuID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getMenuPermissions, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModulePermissions = `-- name: GetModulePermissions :many
SELECT p.id, p.name, p.code, p.description, p.metadata, p.created_at FROM permissions p
INNER JOIN module_permissions mp ON p.id = mp.permission_id
WHERE mp.module_id = $1
`

func (q *Queries) GetModulePermissions(ctx context.Context, moduleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getModulePermissions, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermission = `-- name: GetPermission :one
SELECT id, name, code, description, metadata, created_at FROM permissions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPermission(ctx context.Context, id int32) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, name, code, description, metadata, created_at FROM permissions WHERE code = $1 LIMIT 1
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getRolePermissionsWithScope = `-- name: GetRolePermissionsWithScope :many


SELECT p.id, p.name, p.code, p.description, p.metadata, p.created_at, rp.scope FROM permissions p
INNER JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

type GetRolePermissionsWithScopeRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Description pgtype.Text      `json:"description"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Scope       pgtype.Text      `json:"scope"`
}

// =====================================================
// ROLES
// Note: Role queries are in roles_query.sql
// =====================================================
// =====================================================
// ROLE PERMISSIONS
// Note: AssignPermissionToRole and GetRolePermissions are in roles_query.sql
// =====================================================
func (q *Queries) GetRolePermissionsWithScope(ctx context.Context, roleID int32) ([]GetRolePermissionsWithScopeRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissionsWithScope, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolePermissionsWithScopeRow
	for rows.Next() {
		var i GetRolePermissionsWithScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmenuPermissions = `-- name: GetSubmenuPermissions :many
SELECT p.id, p.name, p.code, p.description, p.metadata, p.created_at FROM permissions p
INNER JOIN submenu_permissions sp ON p.id = sp.permission_id
WHERE sp.submenu_id = $1
`

func (q *Queries) GetSubmenuPermissions(ctx context.Context, submenuID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getSubmenuPermissions, submenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccessibleMenus = `-- name: GetUserAccessibleMenus :many
SELECT DISTINCT mn.id, mn.module_id, mn.parent_menu_id, mn.name, mn.code, mn.route_path, mn.icon, mn.display_order, mn.is_active, mn.metadata, mn.created_at, mn.updated_at FROM menus mn
INNER JOIN menu_permissions mnp ON mn.id = mnp.menu_id
INNER JOIN role_permissions rp ON mnp.permission_id = rp.permission_id
INNER JOIN user_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1 AND mn.is_active = true
ORDER BY mn.display_order
`

func (q *Queries) GetUserAccessibleMenus(ctx context.Context, userID int32) ([]Menu, error) {
	rows, err := q.db.Query(ctx, getUserAccessibleMenus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.ParentMenuID,
			&i.Name,
			&i.Code,
			&i.RoutePath,
			&i.Icon,
			&i.DisplayOrder,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccessibleModules = `-- name: GetUserAccessibleModules :many
SELECT DISTINCT m.id, m.name, m.code, m.description, m.icon, m.is_active, m.display_order, m.metadata, m.created_at, m.updated_at FROM modules m
INNER JOIN module_permissions mp ON m.id = mp.module_id
INNER JOIN role_permissions rp ON mp.permission_id = rp.permission_id
INNER JOIN user_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1 AND m.is_active = true
ORDER BY m.display_order
`

func (q *Queries) GetUserAccessibleModules(ctx context.Context, userID int32) ([]Module, error) {
	rows, err := q.db.Query(ctx, getUserAccessibleModules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Icon,
			&i.IsActive,
			&i.DisplayOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccessibleSubmenus = `-- name: GetUserAccessibleSubmenus :many
SELECT DISTINCT sm.id, sm.menu_id, sm.parent_submenu_id, sm.name, sm.code, sm.route_path, sm.icon, sm.display_order, sm.is_active, sm.metadata, sm.created_at, sm.updated_at FROM submenus sm
INNER JOIN submenu_permissions sp ON sm.id = sp.submenu_id
INNER JOIN role_permissions rp ON sp.permission_id = rp.permission_id
INNER JOIN user_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1 AND sm.is_active = true
ORDER BY sm.display_order
`

func (q *Queries) GetUserAccessibleSubmenus(ctx context.Context, userID int32) ([]Submenu, error) {
	rows, err := q.db.Query(ctx, getUserAccessibleSubmenus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submenu
	for rows.Next() {
		var i Submenu
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentSubmenuID,
			&i.Name,
			&i.Code,
			&i.RoutePath,
			&i.Icon,
			&i.DisplayOrder,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many

SELECT DISTINCT p.id, p.name, p.code, p.description, p.metadata, p.created_at FROM permissions p
INNER JOIN role_permissions rp ON p.id = rp.permission_id
INNER JOIN user_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1
`

// =====================================================
// USER PERMISSIONS (via roles)
// =====================================================
func (q *Queries) GetUserPermissions(ctx context.Context, userID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionsWithScope = `-- name: GetUserPermissionsWithScope :many
SELECT DISTINCT p.id, p.name, p.code, p.description, p.metadata, p.created_at, rp.scope FROM permissions p
INNER JOIN role_permissions rp ON p.id = rp.permission_id
INNER JOIN user_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1
`

type GetUserPermissionsWithScopeRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Description pgtype.Text      `json:"description"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Scope       pgtype.Text      `json:"scope"`
}

func (q *Queries) GetUserPermissionsWithScope(ctx context.Context, userID int32) ([]GetUserPermissionsWithScopeRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsWithScope, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPermissionsWithScopeRow
	for rows.Next() {
		var i GetUserPermissionsWithScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, code, description, metadata, created_at FROM permissions
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermissionFromMenu = `-- name: RevokePermissionFromMenu :exec
DELETE FROM menu_permissions 
WHERE menu_id = $1 AND permission_id = $2
`

type RevokePermissionFromMenuParams struct {
	MenuID       int32 `json:"menu_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromMenu(ctx context.Context, arg RevokePermissionFromMenuParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromMenu, arg.MenuID, arg.PermissionID)
	return err
}

const revokePermissionFromModule = `-- name: RevokePermissionFromModule :exec
DELETE FROM module_permissions 
WHERE module_id = $1 AND permission_id = $2
`

type RevokePermissionFromModuleParams struct {
	ModuleID     int32 `json:"module_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromModule(ctx context.Context, arg RevokePermissionFromModuleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromModule, arg.ModuleID, arg.PermissionID)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions 
WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const revokePermissionFromSubmenu = `-- name: RevokePermissionFromSubmenu :exec
DELETE FROM submenu_permissions 
WHERE submenu_id = $1 AND permission_id = $2
`

type RevokePermissionFromSubmenuParams struct {
	SubmenuID    int32 `json:"submenu_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromSubmenu(ctx context.Context, arg RevokePermissionFromSubmenuParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromSubmenu, arg.SubmenuID, arg.PermissionID)
	return err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET 
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    metadata = COALESCE($3, metadata)
WHERE id = $4
RETURNING id, name, code, description, metadata, created_at
`

type UpdatePermissionParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Metadata    []byte      `json:"metadata"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.Name,
		arg.Description,
		arg.Metadata,
		arg.ID,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const updateRolePermissionScope = `-- name: UpdateRolePermissionScope :one

UPDATE role_permissions
SET scope = $3
WHERE role_id = $1 AND permission_id = $2
RETURNING id, role_id, permission_id, scope, metadata, created_at
`

type UpdateRolePermissionScopeParams struct {
	RoleID       int32       `json:"role_id"`
	PermissionID int32       `json:"permission_id"`
	Scope        pgtype.Text `json:"scope"`
}

// Note: CheckRoleHasPermission is in roles_query.sql
func (q *Queries) UpdateRolePermissionScope(ctx context.Context, arg UpdateRolePermissionScopeParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, updateRolePermissionScope, arg.RoleID, arg.PermissionID, arg.Scope)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PermissionID,
		&i.Scope,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
