// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_mappings_query.sql

package repository

import (
	"context"
)

const checkUserHasMenuAccess = `-- name: CheckUserHasMenuAccess :one
SELECT EXISTS(
    SELECT 1 
    FROM user_roles ur
    JOIN role_permissions rp ON ur.role_id = rp.role_id
    JOIN menu_permissions mp ON rp.permission_id = mp.permission_id
    WHERE ur.user_id = $1 AND mp.menu_id = $2
) AS has_access
`

type CheckUserHasMenuAccessParams struct {
	UserID int32 `json:"user_id"`
	MenuID int32 `json:"menu_id"`
}

func (q *Queries) CheckUserHasMenuAccess(ctx context.Context, arg CheckUserHasMenuAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasMenuAccess, arg.UserID, arg.MenuID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const checkUserHasModuleAccess = `-- name: CheckUserHasModuleAccess :one
SELECT EXISTS(
    SELECT 1 
    FROM user_roles ur
    JOIN role_permissions rp ON ur.role_id = rp.role_id
    JOIN module_permissions mp ON rp.permission_id = mp.permission_id
    WHERE ur.user_id = $1 AND mp.module_id = $2
) AS has_access
`

type CheckUserHasModuleAccessParams struct {
	UserID   int32 `json:"user_id"`
	ModuleID int32 `json:"module_id"`
}

func (q *Queries) CheckUserHasModuleAccess(ctx context.Context, arg CheckUserHasModuleAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasModuleAccess, arg.UserID, arg.ModuleID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const checkUserHasSubmenuAccess = `-- name: CheckUserHasSubmenuAccess :one
SELECT EXISTS(
    SELECT 1 
    FROM user_roles ur
    JOIN role_permissions rp ON ur.role_id = rp.role_id
    JOIN submenu_permissions sp ON rp.permission_id = sp.permission_id
    WHERE ur.user_id = $1 AND sp.submenu_id = $2
) AS has_access
`

type CheckUserHasSubmenuAccessParams struct {
	UserID    int32 `json:"user_id"`
	SubmenuID int32 `json:"submenu_id"`
}

func (q *Queries) CheckUserHasSubmenuAccess(ctx context.Context, arg CheckUserHasSubmenuAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasSubmenuAccess, arg.UserID, arg.SubmenuID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const createMenuPermission = `-- name: CreateMenuPermission :one
INSERT INTO menu_permissions (
    menu_id,
    permission_id,
    metadata
) VALUES (
    $1, $2, $3
) RETURNING id, menu_id, permission_id, metadata
`

type CreateMenuPermissionParams struct {
	MenuID       int32  `json:"menu_id"`
	PermissionID int32  `json:"permission_id"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreateMenuPermission(ctx context.Context, arg CreateMenuPermissionParams) (MenuPermission, error) {
	row := q.db.QueryRow(ctx, createMenuPermission, arg.MenuID, arg.PermissionID, arg.Metadata)
	var i MenuPermission
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const createModulePermission = `-- name: CreateModulePermission :one
INSERT INTO module_permissions (
    module_id,
    permission_id,
    metadata
) VALUES (
    $1, $2, $3
) RETURNING id, module_id, permission_id, metadata
`

type CreateModulePermissionParams struct {
	ModuleID     int32  `json:"module_id"`
	PermissionID int32  `json:"permission_id"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreateModulePermission(ctx context.Context, arg CreateModulePermissionParams) (ModulePermission, error) {
	row := q.db.QueryRow(ctx, createModulePermission, arg.ModuleID, arg.PermissionID, arg.Metadata)
	var i ModulePermission
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const createSubmenuPermission = `-- name: CreateSubmenuPermission :one
INSERT INTO submenu_permissions (
    submenu_id,
    permission_id,
    metadata
) VALUES (
    $1, $2, $3
) RETURNING id, submenu_id, permission_id, metadata
`

type CreateSubmenuPermissionParams struct {
	SubmenuID    int32  `json:"submenu_id"`
	PermissionID int32  `json:"permission_id"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreateSubmenuPermission(ctx context.Context, arg CreateSubmenuPermissionParams) (SubmenuPermission, error) {
	row := q.db.QueryRow(ctx, createSubmenuPermission, arg.SubmenuID, arg.PermissionID, arg.Metadata)
	var i SubmenuPermission
	err := row.Scan(
		&i.ID,
		&i.SubmenuID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const deleteMenuPermission = `-- name: DeleteMenuPermission :exec
DELETE FROM menu_permissions
WHERE menu_id = $1 AND permission_id = $2
`

type DeleteMenuPermissionParams struct {
	MenuID       int32 `json:"menu_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) DeleteMenuPermission(ctx context.Context, arg DeleteMenuPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteMenuPermission, arg.MenuID, arg.PermissionID)
	return err
}

const deleteModulePermission = `-- name: DeleteModulePermission :exec
DELETE FROM module_permissions
WHERE module_id = $1 AND permission_id = $2
`

type DeleteModulePermissionParams struct {
	ModuleID     int32 `json:"module_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) DeleteModulePermission(ctx context.Context, arg DeleteModulePermissionParams) error {
	_, err := q.db.Exec(ctx, deleteModulePermission, arg.ModuleID, arg.PermissionID)
	return err
}

const deleteSubmenuPermission = `-- name: DeleteSubmenuPermission :exec
DELETE FROM submenu_permissions
WHERE submenu_id = $1 AND permission_id = $2
`

type DeleteSubmenuPermissionParams struct {
	SubmenuID    int32 `json:"submenu_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) DeleteSubmenuPermission(ctx context.Context, arg DeleteSubmenuPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteSubmenuPermission, arg.SubmenuID, arg.PermissionID)
	return err
}

const getMenuPermission = `-- name: GetMenuPermission :one
SELECT id, menu_id, permission_id, metadata FROM menu_permissions
WHERE id = $1
`

func (q *Queries) GetMenuPermission(ctx context.Context, id int32) (MenuPermission, error) {
	row := q.db.QueryRow(ctx, getMenuPermission, id)
	var i MenuPermission
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const getModulePermission = `-- name: GetModulePermission :one
SELECT id, module_id, permission_id, metadata FROM module_permissions
WHERE id = $1
`

func (q *Queries) GetModulePermission(ctx context.Context, id int32) (ModulePermission, error) {
	row := q.db.QueryRow(ctx, getModulePermission, id)
	var i ModulePermission
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const getSubmenuPermission = `-- name: GetSubmenuPermission :one
SELECT id, submenu_id, permission_id, metadata FROM submenu_permissions
WHERE id = $1
`

func (q *Queries) GetSubmenuPermission(ctx context.Context, id int32) (SubmenuPermission, error) {
	row := q.db.QueryRow(ctx, getSubmenuPermission, id)
	var i SubmenuPermission
	err := row.Scan(
		&i.ID,
		&i.SubmenuID,
		&i.PermissionID,
		&i.Metadata,
	)
	return i, err
}

const listMenuPermissions = `-- name: ListMenuPermissions :many
SELECT mp.id, mp.menu_id, mp.permission_id, mp.metadata, m.name AS menu_name, p.name AS permission_name
FROM menu_permissions mp
JOIN menus m ON mp.menu_id = m.id
JOIN permissions p ON mp.permission_id = p.id
ORDER BY m.name, p.name
`

type ListMenuPermissionsRow struct {
	ID             int32  `json:"id"`
	MenuID         int32  `json:"menu_id"`
	PermissionID   int32  `json:"permission_id"`
	Metadata       []byte `json:"metadata"`
	MenuName       string `json:"menu_name"`
	PermissionName string `json:"permission_name"`
}

func (q *Queries) ListMenuPermissions(ctx context.Context) ([]ListMenuPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listMenuPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuPermissionsRow
	for rows.Next() {
		var i ListMenuPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.PermissionID,
			&i.Metadata,
			&i.MenuName,
			&i.PermissionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuPermissionsByMenu = `-- name: ListMenuPermissionsByMenu :many
SELECT mp.id, mp.menu_id, mp.permission_id, mp.metadata, p.name AS permission_name, p.code AS permission_code
FROM menu_permissions mp
JOIN permissions p ON mp.permission_id = p.id
WHERE mp.menu_id = $1
ORDER BY p.name
`

type ListMenuPermissionsByMenuRow struct {
	ID             int32  `json:"id"`
	MenuID         int32  `json:"menu_id"`
	PermissionID   int32  `json:"permission_id"`
	Metadata       []byte `json:"metadata"`
	PermissionName string `json:"permission_name"`
	PermissionCode string `json:"permission_code"`
}

func (q *Queries) ListMenuPermissionsByMenu(ctx context.Context, menuID int32) ([]ListMenuPermissionsByMenuRow, error) {
	rows, err := q.db.Query(ctx, listMenuPermissionsByMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuPermissionsByMenuRow
	for rows.Next() {
		var i ListMenuPermissionsByMenuRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.PermissionID,
			&i.Metadata,
			&i.PermissionName,
			&i.PermissionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulePermissions = `-- name: ListModulePermissions :many
SELECT mp.id, mp.module_id, mp.permission_id, mp.metadata, m.name AS module_name, p.name AS permission_name
FROM module_permissions mp
JOIN modules m ON mp.module_id = m.id
JOIN permissions p ON mp.permission_id = p.id
ORDER BY m.name, p.name
`

type ListModulePermissionsRow struct {
	ID             int32  `json:"id"`
	ModuleID       int32  `json:"module_id"`
	PermissionID   int32  `json:"permission_id"`
	Metadata       []byte `json:"metadata"`
	ModuleName     string `json:"module_name"`
	PermissionName string `json:"permission_name"`
}

func (q *Queries) ListModulePermissions(ctx context.Context) ([]ListModulePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listModulePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModulePermissionsRow
	for rows.Next() {
		var i ListModulePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.PermissionID,
			&i.Metadata,
			&i.ModuleName,
			&i.PermissionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulePermissionsByModule = `-- name: ListModulePermissionsByModule :many
SELECT mp.id, mp.module_id, mp.permission_id, mp.metadata, p.name AS permission_name, p.code AS permission_code
FROM module_permissions mp
JOIN permissions p ON mp.permission_id = p.id
WHERE mp.module_id = $1
ORDER BY p.name
`

type ListModulePermissionsByModuleRow struct {
	ID             int32  `json:"id"`
	ModuleID       int32  `json:"module_id"`
	PermissionID   int32  `json:"permission_id"`
	Metadata       []byte `json:"metadata"`
	PermissionName string `json:"permission_name"`
	PermissionCode string `json:"permission_code"`
}

func (q *Queries) ListModulePermissionsByModule(ctx context.Context, moduleID int32) ([]ListModulePermissionsByModuleRow, error) {
	rows, err := q.db.Query(ctx, listModulePermissionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModulePermissionsByModuleRow
	for rows.Next() {
		var i ListModulePermissionsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.PermissionID,
			&i.Metadata,
			&i.PermissionName,
			&i.PermissionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmenuPermissions = `-- name: ListSubmenuPermissions :many
SELECT sp.id, sp.submenu_id, sp.permission_id, sp.metadata, s.name AS submenu_name, p.name AS permission_name
FROM submenu_permissions sp
JOIN submenus s ON sp.submenu_id = s.id
JOIN permissions p ON sp.permission_id = p.id
ORDER BY s.name, p.name
`

type ListSubmenuPermissionsRow struct {
	ID             int32  `json:"id"`
	SubmenuID      int32  `json:"submenu_id"`
	PermissionID   int32  `json:"permission_id"`
	Metadata       []byte `json:"metadata"`
	SubmenuName    string `json:"submenu_name"`
	PermissionName string `json:"permission_name"`
}

func (q *Queries) ListSubmenuPermissions(ctx context.Context) ([]ListSubmenuPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmenuPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmenuPermissionsRow
	for rows.Next() {
		var i ListSubmenuPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmenuID,
			&i.PermissionID,
			&i.Metadata,
			&i.SubmenuName,
			&i.PermissionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmenuPermissionsBySubmenu = `-- name: ListSubmenuPermissionsBySubmenu :many
SELECT sp.id, sp.submenu_id, sp.permission_id, sp.metadata, p.name AS permission_name, p.code AS permission_code
FROM submenu_permissions sp
JOIN permissions p ON sp.permission_id = p.id
WHERE sp.submenu_id = $1
ORDER BY p.name
`

type ListSubmenuPermissionsBySubmenuRow struct {
	ID             int32  `json:"id"`
	SubmenuID      int32  `json:"submenu_id"`
	PermissionID   int32  `json:"permission_id"`
	Metadata       []byte `json:"metadata"`
	PermissionName string `json:"permission_name"`
	PermissionCode string `json:"permission_code"`
}

func (q *Queries) ListSubmenuPermissionsBySubmenu(ctx context.Context, submenuID int32) ([]ListSubmenuPermissionsBySubmenuRow, error) {
	rows, err := q.db.Query(ctx, listSubmenuPermissionsBySubmenu, submenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmenuPermissionsBySubmenuRow
	for rows.Next() {
		var i ListSubmenuPermissionsBySubmenuRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmenuID,
			&i.PermissionID,
			&i.Metadata,
			&i.PermissionName,
			&i.PermissionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
