// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_movements_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
    movement_type,
    reference_type,
    reference_id,
    product_id,
    product_variant_id,
    from_store_id,
    to_store_id,
    from_location_id,
    to_location_id,
    quantity,
    uom_id,
    batch_number,
    serial_number,
    movement_date,
    posted_by,
    status,
    cost_per_unit,
    total_value,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at
`

type CreateStockMovementParams struct {
	MovementType     string           `json:"movement_type"`
	ReferenceType    pgtype.Text      `json:"reference_type"`
	ReferenceID      pgtype.Int4      `json:"reference_id"`
	ProductID        int32            `json:"product_id"`
	ProductVariantID pgtype.Int4      `json:"product_variant_id"`
	FromStoreID      pgtype.Int4      `json:"from_store_id"`
	ToStoreID        pgtype.Int4      `json:"to_store_id"`
	FromLocationID   pgtype.Int4      `json:"from_location_id"`
	ToLocationID     pgtype.Int4      `json:"to_location_id"`
	Quantity         pgtype.Numeric   `json:"quantity"`
	UomID            pgtype.Int4      `json:"uom_id"`
	BatchNumber      pgtype.Text      `json:"batch_number"`
	SerialNumber     pgtype.Text      `json:"serial_number"`
	MovementDate     pgtype.Timestamp `json:"movement_date"`
	PostedBy         pgtype.Int4      `json:"posted_by"`
	Status           pgtype.Text      `json:"status"`
	CostPerUnit      pgtype.Numeric   `json:"cost_per_unit"`
	TotalValue       pgtype.Numeric   `json:"total_value"`
	Metadata         []byte           `json:"metadata"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.MovementType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.FromStoreID,
		arg.ToStoreID,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.Quantity,
		arg.UomID,
		arg.BatchNumber,
		arg.SerialNumber,
		arg.MovementDate,
		arg.PostedBy,
		arg.Status,
		arg.CostPerUnit,
		arg.TotalValue,
		arg.Metadata,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.MovementType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Quantity,
		&i.UomID,
		&i.BatchNumber,
		&i.SerialNumber,
		&i.MovementDate,
		&i.PostedBy,
		&i.Status,
		&i.CostPerUnit,
		&i.TotalValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getStockMovement = `-- name: GetStockMovement :one
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE id = $1
`

func (q *Queries) GetStockMovement(ctx context.Context, id int32) (StockMovement, error) {
	row := q.db.QueryRow(ctx, getStockMovement, id)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.MovementType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Quantity,
		&i.UomID,
		&i.BatchNumber,
		&i.SerialNumber,
		&i.MovementDate,
		&i.PostedBy,
		&i.Status,
		&i.CostPerUnit,
		&i.TotalValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getStockMovementSummaryByProduct = `-- name: GetStockMovementSummaryByProduct :one
SELECT 
    product_id,
    SUM(CASE WHEN to_store_id = $2 THEN quantity ELSE 0 END) AS total_in,
    SUM(CASE WHEN from_store_id = $2 THEN quantity ELSE 0 END) AS total_out,
    SUM(CASE WHEN to_store_id = $2 THEN total_value ELSE 0 END) AS value_in,
    SUM(CASE WHEN from_store_id = $2 THEN total_value ELSE 0 END) AS value_out
FROM stock_movements
WHERE product_id = $1
  AND movement_date >= $3 AND movement_date <= $4
GROUP BY product_id
`

type GetStockMovementSummaryByProductParams struct {
	ProductID      int32            `json:"product_id"`
	ToStoreID      pgtype.Int4      `json:"to_store_id"`
	MovementDate   pgtype.Timestamp `json:"movement_date"`
	MovementDate_2 pgtype.Timestamp `json:"movement_date_2"`
}

type GetStockMovementSummaryByProductRow struct {
	ProductID int32 `json:"product_id"`
	TotalIn   int64 `json:"total_in"`
	TotalOut  int64 `json:"total_out"`
	ValueIn   int64 `json:"value_in"`
	ValueOut  int64 `json:"value_out"`
}

func (q *Queries) GetStockMovementSummaryByProduct(ctx context.Context, arg GetStockMovementSummaryByProductParams) (GetStockMovementSummaryByProductRow, error) {
	row := q.db.QueryRow(ctx, getStockMovementSummaryByProduct,
		arg.ProductID,
		arg.ToStoreID,
		arg.MovementDate,
		arg.MovementDate_2,
	)
	var i GetStockMovementSummaryByProductRow
	err := row.Scan(
		&i.ProductID,
		&i.TotalIn,
		&i.TotalOut,
		&i.ValueIn,
		&i.ValueOut,
	)
	return i, err
}

const getStockMovementsByProductAndStore = `-- name: GetStockMovementsByProductAndStore :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE product_id = $1 
  AND (from_store_id = $2 OR to_store_id = $2)
  AND movement_date >= $3
ORDER BY movement_date DESC
`

type GetStockMovementsByProductAndStoreParams struct {
	ProductID    int32            `json:"product_id"`
	FromStoreID  pgtype.Int4      `json:"from_store_id"`
	MovementDate pgtype.Timestamp `json:"movement_date"`
}

func (q *Queries) GetStockMovementsByProductAndStore(ctx context.Context, arg GetStockMovementsByProductAndStoreParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, getStockMovementsByProductAndStore, arg.ProductID, arg.FromStoreID, arg.MovementDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
ORDER BY movement_date DESC
LIMIT $1 OFFSET $2
`

type ListStockMovementsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovements, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByDateRange = `-- name: ListStockMovementsByDateRange :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE movement_date >= $1 AND movement_date <= $2
ORDER BY movement_date DESC
`

type ListStockMovementsByDateRangeParams struct {
	MovementDate   pgtype.Timestamp `json:"movement_date"`
	MovementDate_2 pgtype.Timestamp `json:"movement_date_2"`
}

func (q *Queries) ListStockMovementsByDateRange(ctx context.Context, arg ListStockMovementsByDateRangeParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByDateRange, arg.MovementDate, arg.MovementDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByProduct = `-- name: ListStockMovementsByProduct :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE product_id = $1
ORDER BY movement_date DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsByProductParams struct {
	ProductID int32 `json:"product_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListStockMovementsByProduct(ctx context.Context, arg ListStockMovementsByProductParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByReference = `-- name: ListStockMovementsByReference :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE reference_type = $1 AND reference_id = $2
ORDER BY movement_date DESC
`

type ListStockMovementsByReferenceParams struct {
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.Int4 `json:"reference_id"`
}

func (q *Queries) ListStockMovementsByReference(ctx context.Context, arg ListStockMovementsByReferenceParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByStore = `-- name: ListStockMovementsByStore :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE from_store_id = $1 OR to_store_id = $1
ORDER BY movement_date DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsByStoreParams struct {
	FromStoreID pgtype.Int4 `json:"from_store_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListStockMovementsByStore(ctx context.Context, arg ListStockMovementsByStoreParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByStore, arg.FromStoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByType = `-- name: ListStockMovementsByType :many
SELECT id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at FROM stock_movements
WHERE movement_type = $1
ORDER BY movement_date DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsByTypeParams struct {
	MovementType string `json:"movement_type"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListStockMovementsByType(ctx context.Context, arg ListStockMovementsByTypeParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByType, arg.MovementType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MovementType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.FromStoreID,
			&i.ToStoreID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.UomID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.MovementDate,
			&i.PostedBy,
			&i.Status,
			&i.CostPerUnit,
			&i.TotalValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockMovementStatus = `-- name: UpdateStockMovementStatus :one
UPDATE stock_movements
SET status = $2
WHERE id = $1
RETURNING id, movement_type, reference_type, reference_id, product_id, product_variant_id, from_store_id, to_store_id, from_location_id, to_location_id, quantity, uom_id, batch_number, serial_number, movement_date, posted_by, status, cost_per_unit, total_value, metadata, created_at
`

type UpdateStockMovementStatusParams struct {
	ID     int32       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateStockMovementStatus(ctx context.Context, arg UpdateStockMovementStatusParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, updateStockMovementStatus, arg.ID, arg.Status)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.MovementType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.FromStoreID,
		&i.ToStoreID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Quantity,
		&i.UomID,
		&i.BatchNumber,
		&i.SerialNumber,
		&i.MovementDate,
		&i.PostedBy,
		&i.Status,
		&i.CostPerUnit,
		&i.TotalValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
