// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: packages/core/grpc/syncpb/sync.proto

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_StreamPush_FullMethodName = "/sync.SyncService/StreamPush"
	SyncService_StreamPull_FullMethodName = "/sync.SyncService/StreamPull"
)

// SyncServiceClient is the client API for SyncService service.
type SyncServiceClient interface {
	// Client-to-Cloud push stream for local outbox items
	StreamPush(ctx context.Context, opts ...grpc.CallOption) (SyncService_StreamPushClient, error)
	// Cloud-to-Client pull stream for incremental delta updates
	StreamPull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (SyncService_StreamPullClient, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) StreamPush(ctx context.Context, opts ...grpc.CallOption) (SyncService_StreamPushClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], SyncService_StreamPush_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &syncServiceStreamPushClient{ClientStream: stream}
	return x, nil
}

type SyncService_StreamPushClient interface {
	Send(*SyncEvent) error
	Recv() (*SyncAck, error)
	grpc.ClientStream
}

type syncServiceStreamPushClient struct {
	grpc.ClientStream
}

func (x *syncServiceStreamPushClient) Send(m *SyncEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *syncServiceStreamPushClient) Recv() (*SyncAck, error) {
	m := new(SyncAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncServiceClient) StreamPull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (SyncService_StreamPullClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[1], SyncService_StreamPull_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &syncServiceStreamPullClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SyncService_StreamPullClient interface {
	Recv() (*SyncEvent, error)
	grpc.ClientStream
}

type syncServiceStreamPullClient struct {
	grpc.ClientStream
}

func (x *syncServiceStreamPullClient) Recv() (*SyncEvent, error) {
	m := new(SyncEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
type SyncServiceServer interface {
	// Client-to-Cloud push stream for local outbox items
	StreamPush(SyncService_StreamPushServer) error
	// Cloud-to-Client pull stream for incremental delta updates
	StreamPull(*PullRequest, SyncService_StreamPullServer) error
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) StreamPush(SyncService_StreamPushServer) error {
	return status.Error(codes.Unimplemented, "method StreamPush not implemented")
}
func (UnimplementedSyncServiceServer) StreamPull(*PullRequest, SyncService_StreamPullServer) error {
	return status.Error(codes.Unimplemented, "method StreamPull not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_StreamPush_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).StreamPush(&syncServiceStreamPushServer{ServerStream: stream})
}

type SyncService_StreamPushServer interface {
	Send(*SyncAck) error
	Recv() (*SyncEvent, error)
	grpc.ServerStream
}

type syncServiceStreamPushServer struct {
	grpc.ServerStream
}

func (x *syncServiceStreamPushServer) Send(m *SyncAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *syncServiceStreamPushServer) Recv() (*SyncEvent, error) {
	m := new(SyncEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SyncService_StreamPull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncServiceServer).StreamPull(m, &syncServiceStreamPullServer{ServerStream: stream})
}

type SyncService_StreamPullServer interface {
	Send(*SyncEvent) error
	grpc.ServerStream
}

type syncServiceStreamPullServer struct {
	grpc.ServerStream
}

func (x *syncServiceStreamPullServer) Send(m *SyncEvent) error {
	return x.ServerStream.SendMsg(m)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPush",
			Handler:       _SyncService_StreamPush_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamPull",
			Handler:       _SyncService_StreamPull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "packages/core/grpc/syncpb/sync.proto",
}
