// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: packages/core/grpc/syncpb/sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncEvent represents a single sync item or binary chunk passed in gRPC stream
type SyncEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Outbox item ID / Sequence ID
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`           // Domain entity type (e.g. pos_transactions, product_barcodes)
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                // Entity primary key ID
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                                     // Action type: INSERT, UPDATE, DELETE
	PayloadJson   []byte                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`        // Serialized JSON/binary payload
	StoreId       int32                  `protobuf:"varint,6,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`                   // Store ID
	TenantSlug    string                 `protobuf:"bytes,7,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`           // Tenant identifier
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`              // Event creation timestamp
	Sha256        string                 `protobuf:"bytes,9,opt,name=sha256,proto3" json:"sha256,omitempty"`                                     // SHA-256 hex checksum of payload_json
	ChunkOffset   uint64                 `protobuf:"varint,10,opt,name=chunk_offset,json=chunkOffset,proto3" json:"chunk_offset,omitempty"`      // Byte offset for chunked messages (0 if unchunked)
	IsLastChunk   bool                   `protobuf:"varint,11,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`    // True if last chunk or single-chunk message
	CorrelationId string                 `protobuf:"bytes,12,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Group identifier for atomic transaction batches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_packages_core_grpc_syncpb_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packages_core_grpc_syncpb_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_packages_core_grpc_syncpb_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SyncEvent) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SyncEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SyncEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *SyncEvent) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *SyncEvent) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *SyncEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *SyncEvent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *SyncEvent) GetChunkOffset() uint64 {
	if x != nil {
		return x.ChunkOffset
	}
	return 0
}

func (x *SyncEvent) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *SyncEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// SyncAck acknowledges receipt and processing of a SyncEvent
type SyncAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // ID matching SyncEvent
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`       // Entity type acknowledged
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`            // Entity primary key ID
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`                              // True if successfully applied
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error details if failed
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`                                 // SHA-256 checksum verified by receiver
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`    // Processing completion timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAck) Reset() {
	*x = SyncAck{}
	mi := &file_packages_core_grpc_syncpb_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAck) ProtoMessage() {}

func (x *SyncAck) ProtoReflect() protoreflect.Message {
	mi := &file_packages_core_grpc_syncpb_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAck.ProtoReflect.Descriptor instead.
func (*SyncAck) Descriptor() ([]byte, []int) {
	return file_packages_core_grpc_syncpb_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncAck) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncAck) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SyncAck) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SyncAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SyncAck) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *SyncAck) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// PullRequest initiates incremental delta-fetch from Cloud
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`    // Tenant slug
	StoreId       int32                  `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`            // Local store ID
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`                                // Sync watermark timestamp (records updated_at > since)
	EntityTypes   []string               `protobuf:"bytes,4,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"` // Filter requested entities (empty = all)
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // Maximum records to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_packages_core_grpc_syncpb_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_core_grpc_syncpb_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_packages_core_grpc_syncpb_sync_proto_rawDescGZIP(), []int{2}
}

func (x *PullRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *PullRequest) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *PullRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *PullRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *PullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_packages_core_grpc_syncpb_sync_proto protoreflect.FileDescriptor

const file_packages_core_grpc_syncpb_sync_proto_rawDesc = "" +
	"\n" +
	"$packages/core/grpc/syncpb/sync.proto\x12\x04sync\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x03\n" +
	"\tSyncEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\fR\vpayloadJson\x12\x19\n" +
	"\bstore_id\x18\x06 \x01(\x05R\astoreId\x12\x1f\n" +
	"\vtenant_slug\x18\a \x01(\tR\n" +
	"tenantSlug\x129\n" +
	"\n" +
	"event_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x16\n" +
	"\x06sha256\x18\t \x01(\tR\x06sha256\x12!\n" +
	"\fchunk_offset\x18\n" +
	" \x01(\x04R\vchunkOffset\x12\"\n" +
	"\ris_last_chunk\x18\v \x01(\bR\visLastChunk\x12%\n" +
	"\x0ecorrelation_id\x18\f \x01(\tR\rcorrelationId\"\xed\x01\n" +
	"\aSyncAck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12=\n" +
	"\fprocessed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\xb4\x01\n" +
	"\vPullRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x05R\astoreId\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12!\n" +
	"\fentity_types\x18\x04 \x03(\tR\ventityTypes\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit2s\n" +
	"\vSyncService\x120\n" +
	"\n" +
	"StreamPush\x12\x0f.sync.SyncEvent\x1a\r.sync.SyncAck(\x010\x01\x122\n" +
	"\n" +
	"StreamPull\x12\x11.sync.PullRequest\x1a\x0f.sync.SyncEvent0\x01B.Z,github.com/NasTecSol/nembus-core/grpc/syncpbb\x06proto3"

var (
	file_packages_core_grpc_syncpb_sync_proto_rawDescOnce sync.Once
	file_packages_core_grpc_syncpb_sync_proto_rawDescData []byte
)

func file_packages_core_grpc_syncpb_sync_proto_rawDescGZIP() []byte {
	file_packages_core_grpc_syncpb_sync_proto_rawDescOnce.Do(func() {
		file_packages_core_grpc_syncpb_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_core_grpc_syncpb_sync_proto_rawDesc), len(file_packages_core_grpc_syncpb_sync_proto_rawDesc)))
	})
	return file_packages_core_grpc_syncpb_sync_proto_rawDescData
}

var file_packages_core_grpc_syncpb_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packages_core_grpc_syncpb_sync_proto_goTypes = []any{
	(*SyncEvent)(nil),             // 0: sync.SyncEvent
	(*SyncAck)(nil),               // 1: sync.SyncAck
	(*PullRequest)(nil),           // 2: sync.PullRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_packages_core_grpc_syncpb_sync_proto_depIdxs = []int32{
	3, // 0: sync.SyncEvent.event_time:type_name -> google.protobuf.Timestamp
	3, // 1: sync.SyncAck.processed_at:type_name -> google.protobuf.Timestamp
	3, // 2: sync.PullRequest.since:type_name -> google.protobuf.Timestamp
	0, // 3: sync.SyncService.StreamPush:input_type -> sync.SyncEvent
	2, // 4: sync.SyncService.StreamPull:input_type -> sync.PullRequest
	1, // 5: sync.SyncService.StreamPush:output_type -> sync.SyncAck
	0, // 6: sync.SyncService.StreamPull:output_type -> sync.SyncEvent
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packages_core_grpc_syncpb_sync_proto_init() }
func file_packages_core_grpc_syncpb_sync_proto_init() {
	if File_packages_core_grpc_syncpb_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_core_grpc_syncpb_sync_proto_rawDesc), len(file_packages_core_grpc_syncpb_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_core_grpc_syncpb_sync_proto_goTypes,
		DependencyIndexes: file_packages_core_grpc_syncpb_sync_proto_depIdxs,
		MessageInfos:      file_packages_core_grpc_syncpb_sync_proto_msgTypes,
	}.Build()
	File_packages_core_grpc_syncpb_sync_proto = out.File
	file_packages_core_grpc_syncpb_sync_proto_goTypes = nil
	file_packages_core_grpc_syncpb_sync_proto_depIdxs = nil
}
