-- =====================================================
-- SUPPLIERS QUERY FILE — DEPRECATED
-- =====================================================
-- All supplier operations have been migrated to business_partners.sql.
-- Use business_partners with partner_role IN ('supplier', 'vendor') instead.
--
-- Replacement query mapping:
--   CreateSupplier          → CreateBusinessPartner (partner_role='supplier')
--   GetSupplier             → GetBusinessPartner
--   GetSupplierByCode       → GetBusinessPartnerByCode
--   ListSuppliers           → ListSuppliersAsBusinessPartners
--   ListActiveSuppliers     → ListActiveBusinessPartners
--   ListSuppliersByType     → ListBusinessPartners (filter by partner_role)
--   SearchSuppliers         → SearchBusinessPartners
--   UpdateSupplier          → UpdateBusinessPartner
--   DeleteSupplier          → (use ToggleBusinessPartnerActive = false)
--   ToggleSupplierActive    → ToggleBusinessPartnerActive
-- =====================================================
