// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loyalty_rules.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoyaltyRule = `-- name: CreateLoyaltyRule :one
INSERT INTO loyalty_redemption_rules (
    organization_id,
    rule_name,
    points_earning_rate,
    points_redemption_rate,
    min_points_to_redeem,
    max_points_per_txn,
    max_redemption_percent,
    eligible_product_types,
    expiry_days,
    is_active,
    valid_from,
    valid_to,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, organization_id, rule_name, points_earning_rate, points_redemption_rate, min_points_to_redeem, max_points_per_txn, max_redemption_percent, eligible_product_types, expiry_days, is_active, valid_from, valid_to, metadata, created_at, updated_at
`

type CreateLoyaltyRuleParams struct {
	OrganizationID       int32          `json:"organization_id"`
	RuleName             string         `json:"rule_name"`
	PointsEarningRate    pgtype.Numeric `json:"points_earning_rate"`
	PointsRedemptionRate pgtype.Numeric `json:"points_redemption_rate"`
	MinPointsToRedeem    pgtype.Numeric `json:"min_points_to_redeem"`
	MaxPointsPerTxn      pgtype.Numeric `json:"max_points_per_txn"`
	MaxRedemptionPercent pgtype.Numeric `json:"max_redemption_percent"`
	EligibleProductTypes []string       `json:"eligible_product_types"`
	ExpiryDays           pgtype.Int4    `json:"expiry_days"`
	IsActive             pgtype.Bool    `json:"is_active"`
	ValidFrom            pgtype.Date    `json:"valid_from"`
	ValidTo              pgtype.Date    `json:"valid_to"`
	Metadata             []byte         `json:"metadata"`
}

func (q *Queries) CreateLoyaltyRule(ctx context.Context, arg CreateLoyaltyRuleParams) (LoyaltyRedemptionRule, error) {
	row := q.db.QueryRow(ctx, createLoyaltyRule,
		arg.OrganizationID,
		arg.RuleName,
		arg.PointsEarningRate,
		arg.PointsRedemptionRate,
		arg.MinPointsToRedeem,
		arg.MaxPointsPerTxn,
		arg.MaxRedemptionPercent,
		arg.EligibleProductTypes,
		arg.ExpiryDays,
		arg.IsActive,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Metadata,
	)
	var i LoyaltyRedemptionRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleName,
		&i.PointsEarningRate,
		&i.PointsRedemptionRate,
		&i.MinPointsToRedeem,
		&i.MaxPointsPerTxn,
		&i.MaxRedemptionPercent,
		&i.EligibleProductTypes,
		&i.ExpiryDays,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLoyaltyRule = `-- name: DeleteLoyaltyRule :exec
DELETE FROM loyalty_redemption_rules
WHERE id = $1
`

func (q *Queries) DeleteLoyaltyRule(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLoyaltyRule, id)
	return err
}

const getActiveLoyaltyRule = `-- name: GetActiveLoyaltyRule :one
SELECT id, organization_id, rule_name, points_earning_rate, points_redemption_rate, min_points_to_redeem, max_points_per_txn, max_redemption_percent, eligible_product_types, expiry_days, is_active, valid_from, valid_to, metadata, created_at, updated_at FROM loyalty_redemption_rules
WHERE organization_id = $1
  AND is_active = true
  AND (valid_from IS NULL OR valid_from <= CURRENT_DATE)
  AND (valid_to IS NULL OR valid_to >= CURRENT_DATE)
ORDER BY created_at DESC
LIMIT 1
`

// Returns the current active rule for the organization (used at checkout to compute points value)
func (q *Queries) GetActiveLoyaltyRule(ctx context.Context, organizationID int32) (LoyaltyRedemptionRule, error) {
	row := q.db.QueryRow(ctx, getActiveLoyaltyRule, organizationID)
	var i LoyaltyRedemptionRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleName,
		&i.PointsEarningRate,
		&i.PointsRedemptionRate,
		&i.MinPointsToRedeem,
		&i.MaxPointsPerTxn,
		&i.MaxRedemptionPercent,
		&i.EligibleProductTypes,
		&i.ExpiryDays,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoyaltyRule = `-- name: GetLoyaltyRule :one
SELECT id, organization_id, rule_name, points_earning_rate, points_redemption_rate, min_points_to_redeem, max_points_per_txn, max_redemption_percent, eligible_product_types, expiry_days, is_active, valid_from, valid_to, metadata, created_at, updated_at FROM loyalty_redemption_rules
WHERE id = $1
`

func (q *Queries) GetLoyaltyRule(ctx context.Context, id int32) (LoyaltyRedemptionRule, error) {
	row := q.db.QueryRow(ctx, getLoyaltyRule, id)
	var i LoyaltyRedemptionRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleName,
		&i.PointsEarningRate,
		&i.PointsRedemptionRate,
		&i.MinPointsToRedeem,
		&i.MaxPointsPerTxn,
		&i.MaxRedemptionPercent,
		&i.EligibleProductTypes,
		&i.ExpiryDays,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoyaltyRules = `-- name: ListLoyaltyRules :many
SELECT id, organization_id, rule_name, points_earning_rate, points_redemption_rate, min_points_to_redeem, max_points_per_txn, max_redemption_percent, eligible_product_types, expiry_days, is_active, valid_from, valid_to, metadata, created_at, updated_at FROM loyalty_redemption_rules
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLoyaltyRules(ctx context.Context, organizationID int32) ([]LoyaltyRedemptionRule, error) {
	rows, err := q.db.Query(ctx, listLoyaltyRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyRedemptionRule
	for rows.Next() {
		var i LoyaltyRedemptionRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RuleName,
			&i.PointsEarningRate,
			&i.PointsRedemptionRate,
			&i.MinPointsToRedeem,
			&i.MaxPointsPerTxn,
			&i.MaxRedemptionPercent,
			&i.EligibleProductTypes,
			&i.ExpiryDays,
			&i.IsActive,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleLoyaltyRuleActive = `-- name: ToggleLoyaltyRuleActive :one
UPDATE loyalty_redemption_rules
SET is_active = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, rule_name, points_earning_rate, points_redemption_rate, min_points_to_redeem, max_points_per_txn, max_redemption_percent, eligible_product_types, expiry_days, is_active, valid_from, valid_to, metadata, created_at, updated_at
`

type ToggleLoyaltyRuleActiveParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) ToggleLoyaltyRuleActive(ctx context.Context, arg ToggleLoyaltyRuleActiveParams) (LoyaltyRedemptionRule, error) {
	row := q.db.QueryRow(ctx, toggleLoyaltyRuleActive, arg.ID, arg.IsActive)
	var i LoyaltyRedemptionRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleName,
		&i.PointsEarningRate,
		&i.PointsRedemptionRate,
		&i.MinPointsToRedeem,
		&i.MaxPointsPerTxn,
		&i.MaxRedemptionPercent,
		&i.EligibleProductTypes,
		&i.ExpiryDays,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoyaltyRule = `-- name: UpdateLoyaltyRule :one
UPDATE loyalty_redemption_rules
SET
    rule_name              = $2,
    points_earning_rate    = $3,
    points_redemption_rate = $4,
    min_points_to_redeem   = $5,
    max_points_per_txn     = $6,
    max_redemption_percent = $7,
    is_active              = $8,
    valid_from             = $9,
    valid_to               = $10,
    metadata               = $11,
    updated_at             = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, rule_name, points_earning_rate, points_redemption_rate, min_points_to_redeem, max_points_per_txn, max_redemption_percent, eligible_product_types, expiry_days, is_active, valid_from, valid_to, metadata, created_at, updated_at
`

type UpdateLoyaltyRuleParams struct {
	ID                   int32          `json:"id"`
	RuleName             string         `json:"rule_name"`
	PointsEarningRate    pgtype.Numeric `json:"points_earning_rate"`
	PointsRedemptionRate pgtype.Numeric `json:"points_redemption_rate"`
	MinPointsToRedeem    pgtype.Numeric `json:"min_points_to_redeem"`
	MaxPointsPerTxn      pgtype.Numeric `json:"max_points_per_txn"`
	MaxRedemptionPercent pgtype.Numeric `json:"max_redemption_percent"`
	IsActive             pgtype.Bool    `json:"is_active"`
	ValidFrom            pgtype.Date    `json:"valid_from"`
	ValidTo              pgtype.Date    `json:"valid_to"`
	Metadata             []byte         `json:"metadata"`
}

func (q *Queries) UpdateLoyaltyRule(ctx context.Context, arg UpdateLoyaltyRuleParams) (LoyaltyRedemptionRule, error) {
	row := q.db.QueryRow(ctx, updateLoyaltyRule,
		arg.ID,
		arg.RuleName,
		arg.PointsEarningRate,
		arg.PointsRedemptionRate,
		arg.MinPointsToRedeem,
		arg.MaxPointsPerTxn,
		arg.MaxRedemptionPercent,
		arg.IsActive,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Metadata,
	)
	var i LoyaltyRedemptionRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleName,
		&i.PointsEarningRate,
		&i.PointsRedemptionRate,
		&i.MinPointsToRedeem,
		&i.MaxPointsPerTxn,
		&i.MaxRedemptionPercent,
		&i.EligibleProductTypes,
		&i.ExpiryDays,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
