// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurant_promotions.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRestaurantPromotion = `-- name: CreateRestaurantPromotion :one

INSERT INTO restaurant_promotions (
    store_id, code, name, description, promotion_type,
    action_metadata, valid_from, valid_to, schedule_json,
    applies_to, target_menu_item_ids, target_menu_category_ids,
    target_customer_types, target_customer_tiers,
    min_order_amount, min_quantity, coupon_code,
    usage_limit, usage_per_customer, discount_value, is_stackable, is_active,
    created_by, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
) RETURNING id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at
`

type CreateRestaurantPromotionParams struct {
	StoreID               int32            `json:"store_id"`
	Code                  string           `json:"code"`
	Name                  string           `json:"name"`
	Description           pgtype.Text      `json:"description"`
	PromotionType         string           `json:"promotion_type"`
	ActionMetadata        json.RawMessage  `json:"action_metadata"`
	ValidFrom             pgtype.Timestamp `json:"valid_from"`
	ValidTo               pgtype.Timestamp `json:"valid_to"`
	ScheduleJson          json.RawMessage  `json:"schedule_json"`
	AppliesTo             pgtype.Text      `json:"applies_to"`
	TargetMenuItemIds     []int32          `json:"target_menu_item_ids"`
	TargetMenuCategoryIds []int32          `json:"target_menu_category_ids"`
	TargetCustomerTypes   []string         `json:"target_customer_types"`
	TargetCustomerTiers   []string         `json:"target_customer_tiers"`
	MinOrderAmount        pgtype.Numeric   `json:"min_order_amount"`
	MinQuantity           pgtype.Numeric   `json:"min_quantity"`
	CouponCode            pgtype.Text      `json:"coupon_code"`
	UsageLimit            pgtype.Int4      `json:"usage_limit"`
	UsagePerCustomer      pgtype.Int4      `json:"usage_per_customer"`
	DiscountValue         pgtype.Numeric   `json:"discount_value"`
	IsStackable           pgtype.Bool      `json:"is_stackable"`
	IsActive              pgtype.Bool      `json:"is_active"`
	CreatedBy             pgtype.Int4      `json:"created_by"`
	Metadata              json.RawMessage  `json:"metadata"`
}

// =====================================================
// SQLC QUERIES FOR RESTAURANT PROMOTIONS
// Dedicated Restaurant Menu Item & Category Promotion Management
// =====================================================
func (q *Queries) CreateRestaurantPromotion(ctx context.Context, arg CreateRestaurantPromotionParams) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, createRestaurantPromotion,
		arg.StoreID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.PromotionType,
		arg.ActionMetadata,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ScheduleJson,
		arg.AppliesTo,
		arg.TargetMenuItemIds,
		arg.TargetMenuCategoryIds,
		arg.TargetCustomerTypes,
		arg.TargetCustomerTiers,
		arg.MinOrderAmount,
		arg.MinQuantity,
		arg.CouponCode,
		arg.UsageLimit,
		arg.UsagePerCustomer,
		arg.DiscountValue,
		arg.IsStackable,
		arg.IsActive,
		arg.CreatedBy,
		arg.Metadata,
	)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRestaurantPromotion = `-- name: DeleteRestaurantPromotion :exec
DELETE FROM restaurant_promotions
WHERE id = $1
`

func (q *Queries) DeleteRestaurantPromotion(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRestaurantPromotion, id)
	return err
}

const getActiveRestaurantPromotionByCouponCode = `-- name: GetActiveRestaurantPromotionByCouponCode :one
SELECT id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at FROM restaurant_promotions
WHERE coupon_code = $1
  AND store_id = $2
  AND is_active = true
  AND (valid_from IS NULL OR valid_from <= CURRENT_TIMESTAMP)
  AND (valid_to IS NULL OR valid_to >= CURRENT_TIMESTAMP)
  AND (usage_limit IS NULL OR usage_count < usage_limit)
`

type GetActiveRestaurantPromotionByCouponCodeParams struct {
	CouponCode pgtype.Text `json:"coupon_code"`
	StoreID    int32       `json:"store_id"`
}

func (q *Queries) GetActiveRestaurantPromotionByCouponCode(ctx context.Context, arg GetActiveRestaurantPromotionByCouponCodeParams) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, getActiveRestaurantPromotionByCouponCode, arg.CouponCode, arg.StoreID)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantPromotion = `-- name: GetRestaurantPromotion :one
SELECT id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at FROM restaurant_promotions
WHERE id = $1
`

func (q *Queries) GetRestaurantPromotion(ctx context.Context, id int32) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, getRestaurantPromotion, id)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantPromotionByCode = `-- name: GetRestaurantPromotionByCode :one
SELECT id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at FROM restaurant_promotions
WHERE code = $1
  AND store_id = $2
`

type GetRestaurantPromotionByCodeParams struct {
	Code    string `json:"code"`
	StoreID int32  `json:"store_id"`
}

func (q *Queries) GetRestaurantPromotionByCode(ctx context.Context, arg GetRestaurantPromotionByCodeParams) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, getRestaurantPromotionByCode, arg.Code, arg.StoreID)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRestaurantPromotionUsage = `-- name: IncrementRestaurantPromotionUsage :one
UPDATE restaurant_promotions
SET usage_count = usage_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at
`

func (q *Queries) IncrementRestaurantPromotionUsage(ctx context.Context, id int32) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, incrementRestaurantPromotionUsage, id)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRestaurantPromotions = `-- name: ListActiveRestaurantPromotions :many
SELECT id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at FROM restaurant_promotions
WHERE store_id = $1
  AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRestaurantPromotions(ctx context.Context, storeID int32) ([]RestaurantPromotion, error) {
	rows, err := q.db.Query(ctx, listActiveRestaurantPromotions, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestaurantPromotion
	for rows.Next() {
		var i RestaurantPromotion
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.PromotionType,
			&i.ActionMetadata,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ScheduleJson,
			&i.AppliesTo,
			&i.TargetMenuItemIds,
			&i.TargetMenuCategoryIds,
			&i.TargetCustomerTypes,
			&i.TargetCustomerTiers,
			&i.MinOrderAmount,
			&i.MinQuantity,
			&i.CouponCode,
			&i.UsageLimit,
			&i.UsageCount,
			&i.UsagePerCustomer,
			&i.DiscountValue,
			&i.IsStackable,
			&i.IsActive,
			&i.CreatedBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRestaurantPromotions = `-- name: ListAllRestaurantPromotions :many
SELECT id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at FROM restaurant_promotions
WHERE store_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllRestaurantPromotionsParams struct {
	StoreID int32 `json:"store_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListAllRestaurantPromotions(ctx context.Context, arg ListAllRestaurantPromotionsParams) ([]RestaurantPromotion, error) {
	rows, err := q.db.Query(ctx, listAllRestaurantPromotions, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestaurantPromotion
	for rows.Next() {
		var i RestaurantPromotion
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.PromotionType,
			&i.ActionMetadata,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ScheduleJson,
			&i.AppliesTo,
			&i.TargetMenuItemIds,
			&i.TargetMenuCategoryIds,
			&i.TargetCustomerTypes,
			&i.TargetCustomerTiers,
			&i.MinOrderAmount,
			&i.MinQuantity,
			&i.CouponCode,
			&i.UsageLimit,
			&i.UsageCount,
			&i.UsagePerCustomer,
			&i.DiscountValue,
			&i.IsStackable,
			&i.IsActive,
			&i.CreatedBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestaurantPromotion = `-- name: UpdateRestaurantPromotion :one
UPDATE restaurant_promotions
SET name = $2,
    description = $3,
    action_metadata = $4,
    valid_from = $5,
    valid_to = $6,
    schedule_json = $7,
    applies_to = $8,
    target_menu_item_ids = $9,
    target_menu_category_ids = $10,
    target_customer_types = $11,
    target_customer_tiers = $12,
    min_order_amount = $13,
    min_quantity = $14,
    usage_limit = $15,
    usage_per_customer = $16,
    discount_value = $17,
    is_stackable = $18,
    is_active = $19,
    metadata = $20,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at
`

type UpdateRestaurantPromotionParams struct {
	ID                    int32            `json:"id"`
	Name                  string           `json:"name"`
	Description           pgtype.Text      `json:"description"`
	ActionMetadata        json.RawMessage  `json:"action_metadata"`
	ValidFrom             pgtype.Timestamp `json:"valid_from"`
	ValidTo               pgtype.Timestamp `json:"valid_to"`
	ScheduleJson          json.RawMessage  `json:"schedule_json"`
	AppliesTo             pgtype.Text      `json:"applies_to"`
	TargetMenuItemIds     []int32          `json:"target_menu_item_ids"`
	TargetMenuCategoryIds []int32          `json:"target_menu_category_ids"`
	TargetCustomerTypes   []string         `json:"target_customer_types"`
	TargetCustomerTiers   []string         `json:"target_customer_tiers"`
	MinOrderAmount        pgtype.Numeric   `json:"min_order_amount"`
	MinQuantity           pgtype.Numeric   `json:"min_quantity"`
	UsageLimit            pgtype.Int4      `json:"usage_limit"`
	UsagePerCustomer      pgtype.Int4      `json:"usage_per_customer"`
	DiscountValue         pgtype.Numeric   `json:"discount_value"`
	IsStackable           pgtype.Bool      `json:"is_stackable"`
	IsActive              pgtype.Bool      `json:"is_active"`
	Metadata              json.RawMessage  `json:"metadata"`
}

func (q *Queries) UpdateRestaurantPromotion(ctx context.Context, arg UpdateRestaurantPromotionParams) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, updateRestaurantPromotion,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ActionMetadata,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ScheduleJson,
		arg.AppliesTo,
		arg.TargetMenuItemIds,
		arg.TargetMenuCategoryIds,
		arg.TargetCustomerTypes,
		arg.TargetCustomerTiers,
		arg.MinOrderAmount,
		arg.MinQuantity,
		arg.UsageLimit,
		arg.UsagePerCustomer,
		arg.DiscountValue,
		arg.IsStackable,
		arg.IsActive,
		arg.Metadata,
	)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRestaurantPromotionStatus = `-- name: UpdateRestaurantPromotionStatus :one
UPDATE restaurant_promotions
SET is_active = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, store_id, code, name, description, promotion_type, action_metadata, valid_from, valid_to, schedule_json, applies_to, target_menu_item_ids, target_menu_category_ids, target_customer_types, target_customer_tiers, min_order_amount, min_quantity, coupon_code, usage_limit, usage_count, usage_per_customer, discount_value, is_stackable, is_active, created_by, metadata, created_at, updated_at
`

type UpdateRestaurantPromotionStatusParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateRestaurantPromotionStatus(ctx context.Context, arg UpdateRestaurantPromotionStatusParams) (RestaurantPromotion, error) {
	row := q.db.QueryRow(ctx, updateRestaurantPromotionStatus, arg.ID, arg.IsActive)
	var i RestaurantPromotion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PromotionType,
		&i.ActionMetadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ScheduleJson,
		&i.AppliesTo,
		&i.TargetMenuItemIds,
		&i.TargetMenuCategoryIds,
		&i.TargetCustomerTypes,
		&i.TargetCustomerTiers,
		&i.MinOrderAmount,
		&i.MinQuantity,
		&i.CouponCode,
		&i.UsageLimit,
		&i.UsageCount,
		&i.UsagePerCustomer,
		&i.DiscountValue,
		&i.IsStackable,
		&i.IsActive,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
