// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uom_query.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductUOMConversion = `-- name: CreateProductUOMConversion :one
INSERT INTO product_uom_conversions (
    product_id,
    from_uom_id,
    to_uom_id,
    conversion_factor,
    is_default,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, product_id, from_uom_id, to_uom_id, conversion_factor, is_default, metadata, created_at
`

type CreateProductUOMConversionParams struct {
	ProductID        int32           `json:"product_id"`
	FromUomID        int32           `json:"from_uom_id"`
	ToUomID          int32           `json:"to_uom_id"`
	ConversionFactor pgtype.Numeric  `json:"conversion_factor"`
	IsDefault        pgtype.Bool     `json:"is_default"`
	Metadata         json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateProductUOMConversion(ctx context.Context, arg CreateProductUOMConversionParams) (ProductUomConversion, error) {
	row := q.db.QueryRow(ctx, createProductUOMConversion,
		arg.ProductID,
		arg.FromUomID,
		arg.ToUomID,
		arg.ConversionFactor,
		arg.IsDefault,
		arg.Metadata,
	)
	var i ProductUomConversion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.FromUomID,
		&i.ToUomID,
		&i.ConversionFactor,
		&i.IsDefault,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createUnitOfMeasure = `-- name: CreateUnitOfMeasure :one
INSERT INTO units_of_measure (
    code,
    name,
    uom_type,
    decimal_places,
    is_active,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, name, uom_type, decimal_places, is_active, metadata
`

type CreateUnitOfMeasureParams struct {
	Code          string          `json:"code"`
	Name          string          `json:"name"`
	UomType       pgtype.Text     `json:"uom_type"`
	DecimalPlaces pgtype.Int4     `json:"decimal_places"`
	IsActive      pgtype.Bool     `json:"is_active"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateUnitOfMeasure(ctx context.Context, arg CreateUnitOfMeasureParams) (UnitsOfMeasure, error) {
	row := q.db.QueryRow(ctx, createUnitOfMeasure,
		arg.Code,
		arg.Name,
		arg.UomType,
		arg.DecimalPlaces,
		arg.IsActive,
		arg.Metadata,
	)
	var i UnitsOfMeasure
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UomType,
		&i.DecimalPlaces,
		&i.IsActive,
		&i.Metadata,
	)
	return i, err
}

const createUomPackagingTemplatesPipeline = `-- name: CreateUomPackagingTemplatesPipeline :exec

WITH inserted_templates AS (
    -- 1. Extract and insert all templates from the templates array
    INSERT INTO uom_packaging_templates (organization_id, uom_id, name, code, is_active)
    SELECT 
        ($1::jsonb->>'organization_id')::INTEGER,
        ($1::jsonb->>'uom_id')::INTEGER,
        t->>'template_name',
        t->>'template_code',
        COALESCE((t->>'template_active')::BOOLEAN, true)
    FROM jsonb_array_elements($1::jsonb->'templates') AS t
    ON CONFLICT (uom_id, name) DO UPDATE 
    SET code = EXCLUDED.code, 
        is_active = EXCLUDED.is_active,
        uom_id = EXCLUDED.uom_id
    RETURNING id, code
)
INSERT INTO uom_packaging_template_levels (template_id, level_order, uom_id, multiplier)
SELECT 
    it.id AS template_id,
    (lvl->>'level_order')::INTEGER AS level_order,
    -- Resolve UOM ID: lookup existing ID by code
    (SELECT id FROM units_of_measure WHERE code = lvl->>'uom_code' LIMIT 1) AS uom_id,
    (lvl->>'multiplier')::DECIMAL AS multiplier
FROM jsonb_array_elements($1::jsonb->'templates') AS t
JOIN inserted_templates it ON it.code = t->>'template_code'
CROSS JOIN LATERAL jsonb_array_elements(t->'levels') AS lvl
ON CONFLICT (template_id, level_order) DO UPDATE
SET uom_id = EXCLUDED.uom_id,
    multiplier = EXCLUDED.multiplier
`

// ================================
// PIPELINE & LOOKUP QUERIES
// ================================
// 2. Extract and insert levels for all templates dynamically
func (q *Queries) CreateUomPackagingTemplatesPipeline(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.Exec(ctx, createUomPackagingTemplatesPipeline, dollar_1)
	return err
}

const deleteProductUOMConversion = `-- name: DeleteProductUOMConversion :exec
DELETE FROM product_uom_conversions
WHERE id = $1
`

func (q *Queries) DeleteProductUOMConversion(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProductUOMConversion, id)
	return err
}

const deleteUnitOfMeasure = `-- name: DeleteUnitOfMeasure :exec
DELETE FROM units_of_measure
WHERE id = $1
`

func (q *Queries) DeleteUnitOfMeasure(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUnitOfMeasure, id)
	return err
}

const getProductUOMConversion = `-- name: GetProductUOMConversion :one
SELECT id, product_id, from_uom_id, to_uom_id, conversion_factor, is_default, metadata, created_at FROM product_uom_conversions
WHERE product_id = $1 AND from_uom_id = $2 AND to_uom_id = $3
`

type GetProductUOMConversionParams struct {
	ProductID int32 `json:"product_id"`
	FromUomID int32 `json:"from_uom_id"`
	ToUomID   int32 `json:"to_uom_id"`
}

func (q *Queries) GetProductUOMConversion(ctx context.Context, arg GetProductUOMConversionParams) (ProductUomConversion, error) {
	row := q.db.QueryRow(ctx, getProductUOMConversion, arg.ProductID, arg.FromUomID, arg.ToUomID)
	var i ProductUomConversion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.FromUomID,
		&i.ToUomID,
		&i.ConversionFactor,
		&i.IsDefault,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getUnitOfMeasure = `-- name: GetUnitOfMeasure :one
SELECT id, code, name, uom_type, decimal_places, is_active, metadata FROM units_of_measure
WHERE id = $1
`

func (q *Queries) GetUnitOfMeasure(ctx context.Context, id int32) (UnitsOfMeasure, error) {
	row := q.db.QueryRow(ctx, getUnitOfMeasure, id)
	var i UnitsOfMeasure
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UomType,
		&i.DecimalPlaces,
		&i.IsActive,
		&i.Metadata,
	)
	return i, err
}

const getUnitOfMeasureByCode = `-- name: GetUnitOfMeasureByCode :one
SELECT id, code, name, uom_type, decimal_places, is_active, metadata FROM units_of_measure
WHERE code = $1
`

func (q *Queries) GetUnitOfMeasureByCode(ctx context.Context, code string) (UnitsOfMeasure, error) {
	row := q.db.QueryRow(ctx, getUnitOfMeasureByCode, code)
	var i UnitsOfMeasure
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UomType,
		&i.DecimalPlaces,
		&i.IsActive,
		&i.Metadata,
	)
	return i, err
}

const getUomPackagingTemplatesByUomID = `-- name: GetUomPackagingTemplatesByUomID :many
SELECT 
    t.id AS template_id,
    t.name AS template_name,
    t.code AS template_pattern_code,
    t.is_active AS template_is_active,
    -- Aggregates the levels in hierarchical order into a clean JSON array
    jsonb_agg(
        jsonb_build_object(
            'level_order', tl.level_order,
            'multiplier', tl.multiplier,
            'uom_id', u.id,
            'uom_code', u.code,
            'uom_name', u.name,
            'uom_type', u.uom_type,
            'decimal_places', u.decimal_places
        ) ORDER BY tl.level_order
    ) AS levels
FROM uom_packaging_templates t
JOIN uom_packaging_template_levels tl ON t.id = tl.template_id
JOIN units_of_measure u ON tl.uom_id = u.id
WHERE t.uom_id = $1
GROUP BY t.id, t.name, t.code, t.is_active
`

type GetUomPackagingTemplatesByUomIDRow struct {
	TemplateID          int32           `json:"template_id"`
	TemplateName        string          `json:"template_name"`
	TemplatePatternCode string          `json:"template_pattern_code"`
	TemplateIsActive    pgtype.Bool     `json:"template_is_active"`
	Levels              json.RawMessage `json:"levels"`
}

func (q *Queries) GetUomPackagingTemplatesByUomID(ctx context.Context, uomID int32) ([]GetUomPackagingTemplatesByUomIDRow, error) {
	rows, err := q.db.Query(ctx, getUomPackagingTemplatesByUomID, uomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUomPackagingTemplatesByUomIDRow
	for rows.Next() {
		var i GetUomPackagingTemplatesByUomIDRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.TemplateName,
			&i.TemplatePatternCode,
			&i.TemplateIsActive,
			&i.Levels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUnitsOfMeasure = `-- name: ListActiveUnitsOfMeasure :many
SELECT id, code, name, uom_type, decimal_places, is_active, metadata FROM units_of_measure
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveUnitsOfMeasure(ctx context.Context) ([]UnitsOfMeasure, error) {
	rows, err := q.db.Query(ctx, listActiveUnitsOfMeasure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitsOfMeasure
	for rows.Next() {
		var i UnitsOfMeasure
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UomType,
			&i.DecimalPlaces,
			&i.IsActive,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductUOMConversions = `-- name: ListProductUOMConversions :many
SELECT id, product_id, from_uom_id, to_uom_id, conversion_factor, is_default, metadata, created_at FROM product_uom_conversions
WHERE product_id = $1
ORDER BY from_uom_id, to_uom_id
`

func (q *Queries) ListProductUOMConversions(ctx context.Context, productID int32) ([]ProductUomConversion, error) {
	rows, err := q.db.Query(ctx, listProductUOMConversions, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductUomConversion
	for rows.Next() {
		var i ProductUomConversion
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.FromUomID,
			&i.ToUomID,
			&i.ConversionFactor,
			&i.IsDefault,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsByType = `-- name: ListUnitsByType :many
SELECT id, code, name, uom_type, decimal_places, is_active, metadata FROM units_of_measure
WHERE uom_type = $1
ORDER BY name
`

func (q *Queries) ListUnitsByType(ctx context.Context, uomType pgtype.Text) ([]UnitsOfMeasure, error) {
	rows, err := q.db.Query(ctx, listUnitsByType, uomType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitsOfMeasure
	for rows.Next() {
		var i UnitsOfMeasure
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UomType,
			&i.DecimalPlaces,
			&i.IsActive,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsOfMeasure = `-- name: ListUnitsOfMeasure :many
SELECT id, code, name, uom_type, decimal_places, is_active, metadata FROM units_of_measure
ORDER BY name
`

func (q *Queries) ListUnitsOfMeasure(ctx context.Context) ([]UnitsOfMeasure, error) {
	rows, err := q.db.Query(ctx, listUnitsOfMeasure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitsOfMeasure
	for rows.Next() {
		var i UnitsOfMeasure
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UomType,
			&i.DecimalPlaces,
			&i.IsActive,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductUOMConversion = `-- name: UpdateProductUOMConversion :one
UPDATE product_uom_conversions
SET 
    conversion_factor = $2,
    is_default = $3,
    metadata = $4
WHERE id = $1
RETURNING id, product_id, from_uom_id, to_uom_id, conversion_factor, is_default, metadata, created_at
`

type UpdateProductUOMConversionParams struct {
	ID               int32           `json:"id"`
	ConversionFactor pgtype.Numeric  `json:"conversion_factor"`
	IsDefault        pgtype.Bool     `json:"is_default"`
	Metadata         json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateProductUOMConversion(ctx context.Context, arg UpdateProductUOMConversionParams) (ProductUomConversion, error) {
	row := q.db.QueryRow(ctx, updateProductUOMConversion,
		arg.ID,
		arg.ConversionFactor,
		arg.IsDefault,
		arg.Metadata,
	)
	var i ProductUomConversion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.FromUomID,
		&i.ToUomID,
		&i.ConversionFactor,
		&i.IsDefault,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const updateUnitOfMeasure = `-- name: UpdateUnitOfMeasure :one
UPDATE units_of_measure
SET 
    name = $2,
    uom_type = $3,
    decimal_places = $4,
    is_active = $5,
    metadata = $6
WHERE id = $1
RETURNING id, code, name, uom_type, decimal_places, is_active, metadata
`

type UpdateUnitOfMeasureParams struct {
	ID            int32           `json:"id"`
	Name          string          `json:"name"`
	UomType       pgtype.Text     `json:"uom_type"`
	DecimalPlaces pgtype.Int4     `json:"decimal_places"`
	IsActive      pgtype.Bool     `json:"is_active"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateUnitOfMeasure(ctx context.Context, arg UpdateUnitOfMeasureParams) (UnitsOfMeasure, error) {
	row := q.db.QueryRow(ctx, updateUnitOfMeasure,
		arg.ID,
		arg.Name,
		arg.UomType,
		arg.DecimalPlaces,
		arg.IsActive,
		arg.Metadata,
	)
	var i UnitsOfMeasure
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UomType,
		&i.DecimalPlaces,
		&i.IsActive,
		&i.Metadata,
	)
	return i, err
}
