// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneTenant(arg1:string):Promise<string>;

export function CreateInitialAdmin(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateInitialOrganization(arg1:string,arg2:string):Promise<string>;

export function CreateInitialTenant(arg1:string,arg2:string):Promise<string>;

export function FetchCloudTenants():Promise<any>;

export function GetDBStatus():Promise<string>;

export function InitializeSync():Promise<void>;

export function IsAppSetup():Promise<boolean>;

export function StartDatabase(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function StartSyncService(arg1:string):Promise<void>;
